// Seed content, part 3: Shamakhi, Khinalig, Shahdag, Karabakh and Gabala
// tours (source: Seed_tours.pdf). Same shape and price conventions as
// seedToursBaku.js - see the header there. prices: see the header there.

export const REGIONS_B_TOURS = [
  {
    key: 'shamakhi-basgal-lahij-private',
    operator: 'Qafqaz Tours',
    location: 'Şamaxı',
    category: 'history',
    photo: '/seed/shamakhi-basgal-lahij-private.jpg',
    price: 62, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 1,
    max_participants: 6,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { guide_languages: ['en', 'ar', 'tr'], pickup: true, private: true },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Shamakhi, Basgal and Lahij Private Day Trip',
        summary: 'Discover Shamakhi, Basgal and Lahij on a guided day trip from Baku: the Shamakhi Juma Mosque, Basgal\'s cobbled streets and Lahij\'s copper craftsmanship.',
        highlights: ['Discover the history of the Shamakhi Juma Mosque on a guided day trip', 'Explore the historic settlement of Basgal and its ancient market square', 'Wander through Lahij, a village known for its copper craftsmanship', 'Admire the architectural legacy of Basgal with its cobbled streets', 'Learn about the history of the region from your knowledgeable guide'],
        description: [
          'Begin at the Shamakhi Juma Mosque, one of the oldest mosques in the Caucasus, built in 743. Learn about its history, including its survival through earthquakes and its restoration in 2013.',
          'Next, head to Basgal, a historic settlement in the Ismayilli District. Explore its fortress walls, ancient sewage system, mosques, springs and narrow streets paved with river stones, and discover its earthquake-resistant buildings and unique design features.',
          'Finally, visit Lahij, a village known for centuries-old copper craftsmanship, stone-paved streets and a preserved medieval urban layout. Experience its vibrant craft culture, with artisans working in traditional workshops and houses built from river stone and wood. On the way back you can stop at the Hanging Bridge for a photo (optional).',
        ],
        includes: ['Pickup and drop-off service (Baku area)', 'Air-conditioned transport', 'Certified multilingual guide (English, Arabic, Turkish)', 'Photo shoot with iPhone 17 Pro', 'A bottle of water per person', 'Hanging Bridge photo stop (optional)'],
        excludes: ['Meal', 'Entrance fees'],
        notSuitable: ['Children under 2 years', 'People over 95 years'],
        bring: ['Comfortable shoes', 'Comfortable clothes'],
        notAllowed: ['Smoking in the vehicle', 'Food in the vehicle', 'Alcohol and drugs'],
        know: ['The tour involves walking through historical sites and villages.', 'Some areas may have uneven or cobbled streets.', 'The tour includes visits to religious sites, so dress modestly.', 'Check the weather forecast before the tour.', 'Hanging Bridge fee is 2 AZN.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Şamaxı, Basqal və Lahıc Şəxsi Günlük Turu',
        summary: 'Bakıdan bələdçili günlük turla Şamaxı, Basqal və Lahıcı kəşf edin: Şamaxı Cümə məscidi, Basqalın daş döşənmiş küçələri və Lahıcın mis sənətkarlığı.',
        highlights: ['Bələdçili turda Şamaxı Cümə məscidinin tarixini kəşf edin', 'Basqalın tarixi yaşayış məskənini və qədim bazar meydanını gəzin', 'Mis sənətkarlığı ilə tanınan Lahıc kəndini dolaşın', 'Daş döşənmiş küçələri ilə Basqalın memarlıq irsinə heyran qalın', 'Bilikli bələdçidən regionun tarixini öyrənin'],
        description: [
          'Qafqazın ən qədim məscidlərindən biri olan, 743-cü ildə tikilmiş Şamaxı Cümə məscidindən başlayın. Zəlzələlərdən sağ çıxması və 2013-cü ildə bərpası daxil olmaqla tarixi ilə tanış olun.',
          'Sonra İsmayıllı rayonunda tarixi yaşayış məskəni olan Basqala yollanın. Qala divarlarını, qədim kanalizasiya sistemini, məscidləri, bulaqları və çay daşı ilə döşənmiş dar küçələri kəşf edin, zəlzələyədavamlı binaları və özünəməxsus dizayn xüsusiyyətləri ilə tanış olun.',
          'Nəhayət, əsrlik mis sənətkarlığı, daş döşənmiş küçələri və qorunub saxlanmış orta əsr şəhər planı ilə tanınan Lahıc kəndini ziyarət edin. Ənənəvi emalatxanalarda işləyən sənətkarları, çay daşı və taxtadan tikilmiş evləri ilə canlı sənət mədəniyyətini yaşayın. Geri qayıdarkən foto üçün Asma Körpüdə dayana bilərsiniz (könüllü).',
        ],
        includes: ['Gəliş və qaytarılma xidməti (Bakı ərazisi)', 'Kondisionerli nəqliyyat', 'Sertifikatlı çoxdilli bələdçi (ingilis, ərəb, türk)', 'iPhone 17 Pro ilə foto çəkilişi', 'Adambaşı bir şüşə su', 'Asma Körpüdə foto dayanacağı (könüllü)'],
        excludes: ['Yemək', 'Giriş haqları'],
        notSuitable: ['2 yaşdan kiçik uşaqlar', '95 yaşdan yuxarı şəxslər'],
        bring: ['Rahat ayaqqabı', 'Rahat geyim'],
        notAllowed: ['Avtomobildə siqaret çəkmək', 'Avtomobildə yemək', 'Alkoqol və narkotik maddələr'],
        know: ['Tur tarixi yerlər və kəndlər üzrə piyada gəzintini əhatə edir.', 'Bəzi ərazilərdə küçələr qeyri-bərabər və ya daş döşənmiş ola bilər.', 'Tur dini məkanlara ziyarəti əhatə edir, ona görə mütəvazi geyinin.', 'Turdan əvvəl hava proqnozuna baxın.', 'Asma Körpü haqqı 2 AZN-dir.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Частная поездка в Шемаху, Басгал и Лагидж',
        summary: 'Откройте Шемаху, Басгал и Лагидж на однодневной экскурсии с гидом из Баку: Джума-мечеть Шемахи, мощёные улочки Басгала и медное ремесло Лагиджа.',
        highlights: ['История Джума-мечети Шемахи на экскурсии с гидом', 'Исторический посёлок Басгал и его древняя рыночная площадь', 'Лагидж — деревня, известная медным ремеслом', 'Архитектурное наследие Басгала с его мощёными улицами', 'История региона от знающего гида'],
        description: [
          'Начните с Джума-мечети Шемахи — одной из старейших мечетей Кавказа, построенной в 743 году. Узнайте её историю, включая то, как она пережила землетрясения и была восстановлена в 2013 году.',
          'Затем отправляйтесь в Басгал — исторический посёлок в Исмаиллинском районе. Исследуйте крепостные стены, древнюю канализацию, мечети, родники и узкие улочки, вымощенные речным камнем, а также сейсмостойкие здания и уникальные архитектурные особенности.',
          'Наконец, посетите Лагидж — деревню, известную вековыми традициями обработки меди, мощёными улицами и сохранившейся средневековой планировкой. Почувствуйте живую культуру ремёсел: мастера работают в традиционных мастерских, дома построены из речного камня и дерева. На обратном пути можно сделать остановку у Подвесного моста для фото (по желанию).',
        ],
        includes: ['Трансфер из района Баку и обратно', 'Транспорт с кондиционером', 'Сертифицированный многоязычный гид (английский, арабский, турецкий)', 'Фотосъёмка на iPhone 17 Pro', 'Бутылка воды на человека', 'Фотоостановка у Подвесного моста (по желанию)'],
        excludes: ['Питание', 'Входные билеты'],
        notSuitable: ['Детям до 2 лет', 'Людям старше 95 лет'],
        bring: ['Удобная обувь', 'Удобная одежда'],
        notAllowed: ['Курение в автомобиле', 'Еда в автомобиле', 'Алкоголь и наркотики'],
        know: ['Экскурсия включает прогулки по историческим местам и деревням.', 'Местами улицы могут быть неровными или мощёными камнем.', 'В программе посещение религиозных мест, поэтому одевайтесь скромно.', 'Проверьте прогноз погоды перед поездкой.', 'Вход на Подвесной мост — 2 AZN.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'shamakhi-alpaca-farm',
    operator: 'Caspian Adventures',
    location: 'Şamaxı',
    category: 'entertainment',
    photo: '/seed/shamakhi-alpaca-farm.jpg',
    price: 54, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: '',
    vehicle_features: null,
    facts: { pickup: true, private: false },
    route: 'Pickup point (Baku)',
    i18n: {
      en: {
        title: 'Shamakhi City and Alpaca Farm Tour',
        summary: 'Discover the charming city of Shamakhi on a guided tour from Baku: visit the Diribaba Mausoleum, learn about local history and then meet some adorable alpacas.',
        highlights: ['Shamakhi history', 'Time with alpacas', 'Two tours in one'],
        description: [
          'This day trip is two tours in one. The ancient history of Shamakhi, with its centuries-old touch, will surprise you, and the alpacas will make you smile.',
        ],
        includes: ['Hotel pickup and drop-off', 'Alpaca Azerbaijan: entrance fee', 'Diribaba Mausoleum: entrance fee'],
        excludes: ['Food and drinks', 'Gratuities'],
        notSuitable: ['People with mobility impairments'],
        bring: ['Comfortable shoes', 'Comfortable clothes'],
        notAllowed: ['Luggage or large bags'],
        know: ['This tour takes place rain or shine.'],
        meeting: 'You can be picked up from 6 locations. Choose your location when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Şamaxı Şəhəri və Alpaka Fermasına Tur',
        summary: 'Bakıdan bələdçili turla füsunkar Şamaxı şəhərini kəşf edin: Diribaba türbəsini ziyarət edin, yerli tarixlə tanış olun, sonra sevimli alpakalarla görüşün.',
        highlights: ['Şamaxının tarixi', 'Alpakalarla vaxt', 'Bir turda iki tur'],
        description: [
          'Bu günlük səfər iki turu özündə birləşdirir. Şamaxının qədim tarixi və əsrlərin izləri sizi təəccübləndirəcək, alpakalar isə üzünüzü güldürəcək.',
        ],
        includes: ['Otelə gəliş və qaytarılma', 'Alpaca Azerbaijan: giriş haqqı', 'Diribaba türbəsi: giriş haqqı'],
        excludes: ['Yemək və içkilər', 'Çay pulu'],
        notSuitable: ['Hərəkət məhdudiyyəti olanlar'],
        bring: ['Rahat ayaqqabı', 'Rahat geyim'],
        notAllowed: ['Baqaj və iri çantalar'],
        know: ['Tur yağışlı və ya günəşli havadan asılı olmayaraq keçirilir.'],
        meeting: '6 məntəqədən götürülmək mümkündür. Məntəqəni bron zamanı seçin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Тур по Шемахе и ферма альпак',
        summary: 'Откройте очаровательный город Шемаху на экскурсии с гидом из Баку: посетите мавзолей Дири Баба, узнайте местную историю и познакомьтесь с очаровательными альпаками.',
        highlights: ['История Шемахи', 'Время с альпаками', 'Два тура в одном'],
        description: [
          'Эта однодневная поездка — два тура в одном. Древняя история Шемахи с её вековыми приметами удивит вас, а альпаки заставят улыбаться.',
        ],
        includes: ['Трансфер из отеля и обратно', 'Alpaca Azerbaijan: входной билет', 'Мавзолей Дири Баба: входной билет'],
        excludes: ['Еда и напитки', 'Чаевые'],
        notSuitable: ['Людям с ограниченной подвижностью'],
        bring: ['Удобная обувь', 'Удобная одежда'],
        notAllowed: ['Багаж и большие сумки'],
        know: ['Экскурсия проходит в любую погоду.'],
        meeting: 'Посадка возможна в 6 местах. Выберите место при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'guba-khinalig-candy-cane',
    operator: 'Qafqaz Tours',
    location: 'Quba',
    category: 'nature',
    photo: '/seed/guba-khinalig-candy-cane.jpg',
    price: 40, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 3,
    max_participants: 12,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Guba, Khinalig and Candy Cane Mountain Tour',
        summary: 'A day trip to the stunning village of Khinalig and Candy Cane Mountain, one of the highest villages in Europe, with incredible views and a delicious homemade lunch.',
        highlights: ['One of the highest villages in Europe', 'Canyon road, eagles and mountain views', 'Homemade lunch with national dishes', 'Comfortable bus and experienced guide', 'Visit the Red Jewish Village synagogue'],
        description: [
          'Hotel pickup and Beshbarmag Mountain: after departing from your hotel in Baku, drive straight to the majestic Beshbarmag Mountain, one of Azerbaijan\'s most iconic natural landmarks. Rest, enjoy panoramic views and hear about its spiritual significance and role along the Silk Road.',
          'Candy Cane Mountain: the famous red-and-white striped rock formations, perfect for photos, a light hike and insights into the geological history behind them.',
          'Guba Forest (Gachrash): after passing through Guba city, stop in the lush Gachrash Forest for a short break among tall trees and fresh mountain air.',
          'Red Jewish Village: visit the world-famous Red Jewish Village, the only all-Jewish settlement outside Israel and the USA, and learn about centuries-old traditions and peaceful coexistence.',
          'Gudyalchay River, canyon road and Eagle Mountain: stop at the scenic Gudyalchay River, then drive along the canyon road to Eagle Mountain, where views open over the surrounding valleys. With a bit of luck you may see eagles soaring above the cliffs.',
          'Khinalig Village: the journey concludes at Khinalig, one of the highest and oldest continuously inhabited villages in the Caucasus. Enjoy a traditional home-cooked meal at a local house, followed by visits to the Khinalig Museum and the historic mosque, and learn about the village\'s unique language, customs and way of life. You spend about 1.5 hours exploring.',
        ],
        includes: ['Hotel pickup and drop-off', 'Professional tour guide', 'Entry to Khinalig museums', 'Comfortable bus/transport', 'Lunch (if the option is selected)', 'Customer support'],
        excludes: [],
        notSuitable: ['People with altitude sickness'],
        bring: ['Comfortable shoes'],
        notAllowed: ['Alcohol and drugs'],
        know: ['Please provide your mobile phone number, including the country code.', 'Your guide will contact you the evening before your tour, around 8:00 PM, to confirm your pickup time and location.'],
        meeting: 'Hotel pickup and drop-off in Baku. Your guide will confirm the time and location the evening before.',
      },
      az: {
        title: 'Quba, Xınalıq və Şirin Dağı Turu',
        summary: 'Avropanın ən hündür kəndlərindən biri olan füsunkar Xınalıq kəndinə və Şirin Dağına günlük tur: inanılmaz mənzərələr və dadlı ev yeməyi naharı.',
        highlights: ['Avropanın ən hündür kəndlərindən biri', 'Kanyon yolu, qartallar və dağ mənzərələri', 'Milli yeməklərdən ibarət ev yeməyi naharı', 'Rahat avtobus və təcrübəli bələdçi', 'Qırmızı Qəsəbə sinaqoqunu ziyarət edin'],
        description: [
          'Otelə gəliş və Beşbarmaq dağı: Bakıda otelinizdən yola düşdükdən sonra Azərbaycanın ən məşhur təbii abidələrindən biri olan möhtəşəm Beşbarmaq dağına gedirsiniz. Dincəlin, panoram mənzərələrdən zövq alın və onun mənəvi əhəmiyyəti və İpək Yolu üzərindəki rolu barədə dinləyin.',
          'Şirin Dağı: məşhur qırmızı-ağ zolaqlı qaya formasiyaları; foto, yüngül piyada gəzinti və onların arxasındakı geoloji tarix barədə məlumat üçün idealdır.',
          'Quba meşəsi (Qəçrəş): Quba şəhərindən keçdikdən sonra uca ağaclar və təmiz dağ havası arasında qısa fasilə üçün sıx Qəçrəş meşəsində dayanırsınız.',
          'Qırmızı Qəsəbə: İsrail və ABŞ-dan kənarda yeganə tamamilə yəhudi yaşayış məskəni olan dünyaca məşhur Qırmızı Qəsəbəni ziyarət edin, əsrlik ənənələr və dinc birgəyaşayış haqqında öyrənin.',
          'Qudyalçay, kanyon yolu və Qartal dağı: mənzərəli Qudyalçayda dayanın, sonra kanyon yolu ilə ətraf vadilərin mənzərəsi açılan Qartal dağına gedin. Şansınız olsa, qayalar üzərində uçan qartalları görə bilərsiniz.',
          'Xınalıq kəndi: səyahət Qafqazın ən hündür və ən qədim davamlı məskunlaşmış kəndlərindən biri olan Xınalıqda başa çatır. Yerli evdə ənənəvi ev yeməyi ilə nahar edin, ardınca Xınalıq Muzeyini və tarixi məscidi ziyarət edin, kəndin unikal dili, adətləri və həyat tərzi haqqında öyrənin. Kəşf üçün təxminən 1,5 saat vaxtınız olacaq.',
        ],
        includes: ['Otelə gəliş və qaytarılma', 'Peşəkar tur bələdçisi', 'Xınalıq muzeylərinə giriş', 'Rahat avtobus/nəqliyyat', 'Nahar (seçim edilərsə)', 'Müştəri dəstəyi'],
        excludes: [],
        notSuitable: ['Dağ xəstəliyi olanlar'],
        bring: ['Rahat ayaqqabı'],
        notAllowed: ['Alkoqol və narkotik maddələr'],
        know: ['Zəhmət olmasa ölkə kodu ilə mobil telefon nömrənizi təqdim edin.', 'Bələdçiniz gəliş vaxtını və yerini təsdiqləmək üçün turdan bir gün əvvəl axşam, təxminən saat 20:00-da sizinlə əlaqə saxlayacaq.'],
        meeting: 'Bakıda otelə gəliş və qaytarılma. Bələdçi vaxtı və yeri bir gün əvvəl axşam təsdiqləyəcək.',
      },
      ru: {
        title: 'Тур в Кубу, Хыналыг и на «Леденцовую гору»',
        summary: 'Однодневная поездка в потрясающую деревню Хыналыг и к «Леденцовой горе» — одно из самых высокогорных поселений Европы, с невероятными видами и вкусным домашним обедом.',
        highlights: ['Одна из самых высоких деревень Европы', 'Дорога по каньону, орлы и горные виды', 'Домашний обед с национальными блюдами', 'Комфортабельный автобус и опытный гид', 'Синагога в Красной слободе'],
        description: [
          'Трансфер и гора Бешбармак: после выезда от вашего отеля в Баку вы направитесь к величественной горе Бешбармак — одной из самых знаковых природных достопримечательностей Азербайджана. Отдохните, насладитесь панорамными видами и узнайте о её духовном значении и роли на Шёлковом пути.',
          '«Леденцовая гора»: знаменитые красно-белые полосатые скалы — идеальное место для фото, лёгкой прогулки и рассказа о геологической истории.',
          'Лес Губа (Гечреш): проехав город Губа, остановитесь в зелёном лесу Гечреш для короткого отдыха среди высоких деревьев и свежего горного воздуха.',
          'Красная слобода: посетите всемирно известную Красную слободу — единственное полностью еврейское поселение за пределами Израиля и США — и узнайте о вековых традициях и мирном сосуществовании.',
          'Река Гудиалчай, дорога по каньону и гора Орлиная: остановка у живописной реки Гудиалчай, затем поездка по каньону к горе Орлиной, откуда открываются виды на окрестные долины. Если повезёт, вы увидите парящих над скалами орлов.',
          'Деревня Хыналыг: путешествие завершается в Хыналыге — одном из самых высокогорных и старейших постоянно населённых селений Кавказа. Вас ждёт традиционный домашний обед в местном доме, затем музей Хыналыга и историческая мечеть, рассказ об уникальном языке, обычаях и укладе жизни. На знакомство с деревней отводится около 1,5 часов.',
        ],
        includes: ['Трансфер из отеля и обратно', 'Профессиональный гид', 'Вход в музеи Хыналыга', 'Комфортабельный автобус/транспорт', 'Обед (если выбран вариант)', 'Служба поддержки клиентов'],
        excludes: [],
        notSuitable: ['Людям с горной болезнью'],
        bring: ['Удобная обувь'],
        notAllowed: ['Алкоголь и наркотики'],
        know: ['Пожалуйста, укажите номер мобильного телефона с кодом страны.', 'Гид свяжется с вами накануне вечером, около 20:00, чтобы подтвердить время и место посадки.'],
        meeting: 'Трансфер из отеля в Баку и обратно. Гид подтвердит время и место накануне вечером.',
      },
    },
  },

  {
    key: 'shahdag-2day-quba-gecresh',
    operator: 'Qafqaz Tours',
    location: 'Quba',
    category: 'nature',
    photo: '/seed/shahdag-2day-quba-gecresh.jpg',
    price: 110, // AZN per person, as listed on GetYourGuide
    duration_days: 2,
    min_participants: 2,
    max_participants: 8,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { guide_languages: ['en', 'ru', 'tr'], pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: '2-Day Shahdag Tour: Quba, Candy Cane Mountains and Gecresh',
        summary: 'Escape Baku for 2 days and discover northern Azerbaijan without rushing: the colorful Candy Cane Mountains, iconic Quba, the lush Gecresh Forest and the peaks of Shahdag Mountain Resort.',
        highlights: ['Explore the vibrant, striped Candy Cane Mountains', 'Drive through the dense canopy of Gecresh Forest', 'Discover the mountain waterfalls of Laza Village', 'Enjoy panoramic alpine views at Shahdag Resort'],
        description: [
          'Day 1: Depart Baku and head north toward Khizi. Stop to photograph the surreal pink-and-white-striped shale hills formed by millions of years of iron oxidation. Drive through the dense canopy of ancient trees in Gecresh Forest, with an optional traditional mountain lunch under the trees. In Quba, cross the river to visit the Red Village, the famous historical settlement of Mountain Jews, and take a peaceful walk around nearby Chenlibel Lake. Arrive at Shahdag Mountain Resort in the afternoon, with free time for activities, check-in to your self-booked accommodation, dinner with mountain views and the crisp alpine air.',
          'Day 2: Start with mountain views and free time at Shahdag Mountain Resort: ride the panoramic cable car, try the alpine coaster or enjoy seasonal mountain activities at your own pace. Optionally take a short drive to the ancient village of Laza and walk to the scenic waterfalls surrounded by dramatic cliff walls. Then relax on the comfortable air-conditioned transfer back to Baku, arriving at your hotel or preferred drop-off location.',
          'For reference only. Itineraries are subject to change.',
        ],
        includes: ['Hotel pickup and drop-off in Baku', 'Transportation in an air-conditioned vehicle', 'Professional driver and live guide (English, Russian, Turkish)', 'Bottled water'],
        excludes: ['Accommodation / hotel stay (you book it yourself)', 'Food and drinks', 'Entrance fees and resort activity tickets (cable car, alpine coaster, ski passes)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Accommodation at Shahdag is self-booked.', 'The Laza village and waterfalls visit is optional.'],
        meeting: 'Hotel pickup and drop-off in Baku. Confirm your pickup address when booking.',
      },
      az: {
        title: '2 Günlük Şahdağ Turu: Quba, Şirin Dağlar və Qəçrəş',
        summary: 'Bakıdan 2 günlüyə qaçın və şimal Azərbaycanı tələsmədən kəşf edin: rəngarəng Şirin Dağlar, məşhur Quba, sıx Qəçrəş meşəsi və Şahdağ Dağ Kurortunun zirvələri.',
        highlights: ['Zolaqlı, rəngarəng Şirin Dağları kəşf edin', 'Qəçrəş meşəsinin sıx çətiri altından keçin', 'Laza kəndinin dağ şəlalələrini kəşf edin', 'Şahdag Kurortunda panoram alp mənzərələrindən zövq alın'],
        description: [
          '1-ci gün: Bakıdan yola çıxın və Xızıya doğru şimala gedin. Milyon illik dəmir oksidləşməsindən yaranmış sürreal çəhrayı-ağ zolaqlı şist təpələrini şəkilə çəkmək üçün dayanın. Qəçrəş meşəsinin qədim ağaclarının sıx çətiri altından keçin, könüllü ənənəvi dağ naharı ağaclar altında. Qubada çayı keçərək dağ yəhudilərinin məşhur tarixi yaşayış yeri olan Qırmızı Qəsəbəni ziyarət edin və yaxınlıqdakı Çənlibel gölü ətrafında dinc gəzinti edin. Günortadan sonra Şahdağ Dağ Kurortuna çatın: fəaliyyətlər üçün sərbəst vaxt, özünüz bron etdiyiniz yerləşməyə giriş, dağ mənzərəli şam yeməyi və təmiz alp havası.',
          '2-ci gün: Şahdağ Dağ Kurortunda dağ mənzərələri və sərbəst vaxtla başlayın: panoram kabel yolu ilə qalxın, alp roller-koasterini sınayın və ya mövsümi dağ fəaliyyətlərindən öz tempinizlə zövq alın. Könüllü olaraq qədim Laza kəndinə qısa yol gedib dramatik qaya divarları və zirvələrlə əhatə olunmuş mənzərəli şəlalələrə piyada gedə bilərsiniz. Sonra kondisionerli rahat transferlə Bakıya qayıdın, otelinizə və ya istədiyiniz yerə çatın.',
          'Yalnız məlumat üçün. Marşrut dəyişdirilə bilər.',
        ],
        includes: ['Bakıda otelə gəliş və qaytarılma', 'Kondisionerli avtomobildə nəqliyyat', 'Peşəkar sürücü və canlı bələdçi (ingilis, rus, türk)', 'Şüşə su'],
        excludes: ['Yerləşmə / otel (özünüz bron edirsiniz)', 'Yemək və içkilər', 'Giriş haqları və kurort fəaliyyət biletləri (kabel yolu, alp roller-koasteri, xizək keçidləri)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Şahdağda yerləşməni özünüz bron edirsiniz.', 'Laza kəndi və şəlalələrə ziyarət könüllüdür.'],
        meeting: 'Bakıda otelə gəliş və qaytarılma. Gəliş ünvanını bron zamanı təsdiqləyin.',
      },
      ru: {
        title: '2-дневный тур в Шахдаг: Куба, «Леденцовые горы» и Гечреш',
        summary: 'Сбегите из Баку на 2 дня и откройте север Азербайджана без спешки: красочные «Леденцовые горы», знаменитая Куба, зелёный лес Гечреш и вершины горного курорта Шахдаг.',
        highlights: ['Яркие полосатые «Леденцовые горы»', 'Дорога сквозь густой полог леса Гечреш', 'Горные водопады деревни Лаза', 'Панорамные альпийские виды на курорте Шахдаг'],
        description: [
          'День 1: выезд из Баку на север в сторону Хызы. Остановка для фото сюрреалистичных розово-белых полосатых сланцевых холмов, образовавшихся за миллионы лет окисления железа. Дорога сквозь густой полог древних деревьев леса Гечреш, по желанию — традиционный горный обед под деревьями. В Кубе перейдите реку и посетите Красную слободу — известное историческое поселение горских евреев — и спокойно прогуляйтесь вокруг озера Ченлибель. Во второй половине дня прибытие на горный курорт Шахдаг: свободное время, заселение в самостоятельно забронированное жильё, ужин с видом на горы и свежий альпийский воздух.',
          'День 2: утро на горном курорте Шахдаг со свободным временем — прокатитесь на панорамной канатной дороге, опробуйте альпийский коастер или займитесь сезонными горными развлечениями в своём темпе. По желанию — короткая поездка в древнюю деревню Лаза и прогулка к живописным водопадам среди скалистых стен и вершин. Затем комфортный трансфер с кондиционером обратно в Баку — прямо к отелю или в удобное место.',
          'Только для справки. Маршрут может изменяться.',
        ],
        includes: ['Трансфер из отеля в Баку и обратно', 'Транспорт — автомобиль с кондиционером', 'Профессиональный водитель и живой гид (английский, русский, турецкий)', 'Бутилированная вода'],
        excludes: ['Проживание / отель (бронируется самостоятельно)', 'Еда и напитки', 'Входные билеты и билеты на курортные развлечения (канатная дорога, альпийский коастер, ски-пассы)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Проживание в Шахдаге бронируется самостоятельно.', 'Посещение деревни Лаза и водопадов — по желанию.'],
        meeting: 'Трансфер из отеля в Баку и обратно. Адрес подтверждается при бронировании.',
      },
    },
  },

  {
    key: 'karabakh-khankendi-shusha',
    operator: 'Qafqaz Tours',
    location: 'Xankəndi',
    category: 'nature',
    photo: '/seed/karabakh-khankendi-shusha.jpg',
    price: 90, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 1,
    max_participants: 12,
    features: 'guide',
    vehicle_features: null,
    facts: { pickup: false, private: false },
    route: '191 Lev Tolstoy Street, Baku',
    i18n: {
      en: {
        title: 'Karabakh, Khankendi and Shusha Day Tour',
        summary: 'Be among the first travelers to explore this land of magnificent fortresses, timeless history and stunning landscapes that was closed to visitors for over 30 years.',
        highlights: ['Visit Khankendi and see the Nana Baba Monument and the Parliament Building', 'Explore Shusha, the cultural heart of Karabakh', 'Admire the amazing views of the Caucasus Mountains from the Jidir Duzu Plateau'],
        description: [
          'Join this tour to discover Karabakh, a beautiful land that was closed to visitors for over 30 years. Surrounded by the Caucasus Mountains, Karabakh is full of unique nature, history and culture. In Khankendi, visit the Nana Baba Monument, the Parliament Building and Karabakh University.',
          'Then continue to Shusha, the cultural city of Karabakh. See the Yukhari Govhar Agha Mosque, the Bullet-Riddled Busts and the Natavan House Museum with its famous spring. Explore the strong Shusha Fortress, the M.P. Vagif Mausoleum and enjoy the amazing mountain views from the Jidir Duzu Plateau.',
          'Finish the tour at the legendary Isa Bulagi, known for its clean, fresh water.',
          'The Karabakh Group Tour operates regularly on Mondays, Wednesdays and Saturdays, without any minimum number of guests. If your group has more than 5 participants, you can book the group tour on any day you prefer.',
        ],
        includes: ['Visit to Nana Baba Monument', 'Visit to the Parliament Building', 'Visit to Karabakh University', 'Visit to Yukhari Govhar Agha Mosque', 'Visit to the Bullet-Riddled Busts', '50% cashback on SIM cards', 'Visit to Natavan House Museum', 'Visit to Natavan Spring', 'Walk through Shusha Fortress', 'Visit to M.P. Vagif Mausoleum', 'Visit to Jidir Duzu Plateau', 'Visit to Isa Bulagi'],
        excludes: ['Meals and extra expenses', 'Hotel pickup and drop-off (optional, extra charge)'],
        notSuitable: ['People with mobility impairments'],
        bring: ['Passport', 'Comfortable shoes'],
        notAllowed: ['Pets'],
        know: [
          'The tour involves a significant amount of walking.',
          'Weather can be unpredictable, so dress accordingly.',
          'Guests staying on or around Nizami Street should come to the pickup point.',
          'The Karabakh Group Tour operates regularly on Mondays, Wednesdays and Saturdays without any minimum number of guests.',
          'If your group has more than 5 participants, you can book the group tour on any day you prefer.',
          'The vehicle is provided according to the number of participants.',
        ],
        meeting: 'You can be picked up from 5 locations. Choose your location when booking. Drop-off: 191 Lev Tolstoy Street, Baku AZ1005.',
      },
      az: {
        title: 'Qarabağ, Xankəndi və Şuşa Günlük Turu',
        summary: '30 ildən çox ziyarətçilər üçün bağlı olmuş möhtəşəm qalalar, əbədi tarix və füsunkar mənzərələr diyarını kəşf edən ilk səyyahlardan olun.',
        highlights: ['Xankəndini ziyarət edin, Nənə Baba abidəsini və Parlament binasını görün', 'Qarabağın mədəniyyət mərkəzi Şuşanı kəşf edin', 'Cıdır düzündən Qafqaz dağlarının heyrətamiz mənzərəsinə heyran qalın'],
        description: [
          '30 ildən çox ziyarətçilər üçün bağlı olmuş gözəl diyar Qarabağı kəşf etmək üçün bu tura qoşulun. Qafqaz dağları ilə əhatə olunmuş Qarabağ unikal təbiət, tarix və mədəniyyətlə doludur. Xankəndidə Nənə Baba abidəsini, Parlament binasını və Qarabağ Universitetini ziyarət edin.',
          'Sonra Qarabağın mədəniyyət şəhəri Şuşaya davam edin. Yuxarı Gövhər Ağa məscidini, Güllə yarası olan büstləri və məşhur bulağı ilə Natəvan ev muzeyini görün. Möhkəm Şuşa qalasını, M.P. Vaqif türbəsini gəzin və Cıdır düzündən heyrətamiz dağ mənzərələrindən zövq alın.',
          'Turu təmiz və sərin suyu ilə tanınan əfsanəvi İsa bulağında başa vurun.',
          'Qarabağ Qrup Turu bazar ertəsi, çərşənbə və şənbə günləri müntəzəm keçirilir, minimum qonaq sayı tələb olunmur. Qrupunuz 5-dən çox iştirakçıdırsa, qrup turunu istədiyiniz hər hansı gündə bron edə bilərsiniz.',
        ],
        includes: ['Nənə Baba abidəsinə ziyarət', 'Parlament binasına ziyarət', 'Qarabağ Universitetinə ziyarət', 'Yuxarı Gövhər Ağa məscidinə ziyarət', 'Güllə yarası olan büstlərə ziyarət', 'SİM kartlara 50% keşbek', 'Natəvan ev muzeyinə ziyarət', 'Natəvan bulağına ziyarət', 'Şuşa qalası boyunca gəzinti', 'M.P. Vaqif türbəsinə ziyarət', 'Cıdır düzünə ziyarət', 'İsa bulağına ziyarət'],
        excludes: ['Yemək və əlavə xərclər', 'Otelə gəliş və qaytarılma (könüllü, əlavə haqla)'],
        notSuitable: ['Hərəkət məhdudiyyəti olanlar'],
        bring: ['Pasport', 'Rahat ayaqqabı'],
        notAllowed: ['Ev heyvanları'],
        know: [
          'Tur xeyli piyada gəzintini əhatə edir.',
          'Hava gözlənilməz ola bilər, ona görə uyğun geyinin.',
          'Nizami küçəsində və ya ətrafında qalan qonaqlar gəliş nöqtəsinə gəlməlidir.',
          'Qarabağ Qrup Turu bazar ertəsi, çərşənbə və şənbə günləri müntəzəm keçirilir, minimum qonaq sayı tələb olunmur.',
          'Qrupunuz 5-dən çox iştirakçıdırsa, qrup turunu istədiyiniz hər hansı gündə bron edə bilərsiniz.',
          'Nəqliyyat vasitəsi iştirakçı sayına uyğun təmin edilir.',
        ],
        meeting: '5 məntəqədən götürülmək mümkündür. Məntəqəni bron zamanı seçin. Qaytarılma: Lev Tolstoy küç. 191, Bakı AZ1005.',
      },
      ru: {
        title: 'Однодневный тур по Карабаху: Ханкенди и Шуша',
        summary: 'Станьте одним из первых путешественников, увидевших этот край величественных крепостей, вечной истории и потрясающих пейзажей, закрытый для посетителей более 30 лет.',
        highlights: ['Ханкенди: памятник Нана Баба и здание Парламента', 'Шуша — культурное сердце Карабаха', 'Потрясающие виды на Кавказские горы с плато Джыдыр дюзю'],
        description: [
          'Присоединяйтесь к этому туру, чтобы открыть Карабах — прекрасный край, закрытый для посетителей более 30 лет. Окружённый Кавказскими горами, Карабах полон уникальной природы, истории и культуры. В Ханкенди вы посетите памятник Нана Баба, здание Парламента и Карабахский университет.',
          'Затем отправляйтесь в Шушу — культурный город Карабаха. Вас ждут мечеть Юхары Говхар Ага, простреленные бюсты и дом-музей Натаван со знаменитым родником. Исследуйте мощную Шушинскую крепость, мавзолей М. П. Вагифа и наслаждайтесь горными видами с плато Джыдыр дюзю.',
          'Завершите тур у легендарного родника Иса булаги, известного чистой и свежей водой.',
          'Групповой тур по Карабаху проходит регулярно по понедельникам, средам и субботам без минимального числа гостей. Если в вашей группе больше 5 человек, групповой тур можно забронировать на любой удобный день.',
        ],
        includes: ['Посещение памятника Нана Баба', 'Посещение здания Парламента', 'Посещение Карабахского университета', 'Посещение мечети Юхары Говхар Ага', 'Посещение простреленных бюстов', 'Кэшбэк 50% на SIM-карты', 'Посещение дома-музея Натаван', 'Посещение родника Натаван', 'Прогулка по Шушинской крепости', 'Посещение мавзолея М. П. Вагифа', 'Посещение плато Джыдыр дюзю', 'Посещение родника Иса булаги'],
        excludes: ['Питание и дополнительные расходы', 'Трансфер из отеля и обратно (по желанию, за доплату)'],
        notSuitable: ['Людям с ограниченной подвижностью'],
        bring: ['Паспорт', 'Удобная обувь'],
        notAllowed: ['Домашние животные'],
        know: [
          'Экскурсия подразумевает значительное количество ходьбы.',
          'Погода может быть непредсказуемой, одевайтесь соответственно.',
          'Гостям, проживающим на улице Низами или рядом, нужно подойти к месту посадки.',
          'Групповой тур по Карабаху проходит регулярно по понедельникам, средам и субботам без минимального числа гостей.',
          'Если в вашей группе больше 5 человек, групповой тур можно забронировать на любой удобный день.',
          'Транспорт предоставляется в зависимости от числа участников.',
        ],
        meeting: 'Посадка возможна в 5 местах. Выберите место при бронировании. Высадка: ул. Льва Толстого, 191, Баку AZ1005.',
      },
    },
  },

  {
    key: 'gabala-day-trip',
    operator: 'Caspian Adventures',
    location: 'Qəbələ',
    category: 'nature',
    photo: '/seed/gabala-day-trip.jpg',
    price: 80, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Gabala Day Trip',
        summary: 'A day of sightseeing and relaxation in Gabala\'s stunning natural surroundings: Lake Nohur and the high mountains reflected in the placid water.',
        highlights: ['Relax beside the tranquil Lake Nohur', 'See the Seven Beauties waterfall', 'Try your hand at sports in several world-class facilities'],
        description: [
          'Get picked up from your Baku hotel and drive towards Gabala, with a break in Shamakhi for a bite to eat or a tea. In Gabala, head to Lake Nohur, a pristine lake surrounded by high mountains. Swimming is prohibited (the lake also provides drinking water for Gabala and surrounding regions), but it is perfect for fishing, and you can hop on a boat and explore the lake at your leisure.',
          'Then head to the Seven Beauties waterfall, a seven-tiered waterfall with multiple cascades. Because the trek up the steep slope is quite dangerous, only two of the cascades can be seen. Rest in a seasonal restaurant and teahouse in the cool shade and listen to the rushing water.',
          'Continue to the Tufandag Winter Resort and ride the longest cable car in the world; ski in winter or take in unforgettable summer views of the alpine landscape. Then visit the Gabala Sport Club, a world-class facility that trains professional athletes in shooting, boxing, karate, taekwondo, soccer and judo, and try your hand at shooting where the national Olympic team trains. Head back to Baku after an active day.',
        ],
        includes: ['Professional guide', 'Comfortable sedan', 'Hotel pickup and drop-off', 'Water'],
        excludes: ['Lunch', 'Personal expenses', 'All taxes, fees and handling charges', 'Entrance fees to facilities'],
        notSuitable: ['Pregnant women', 'People with back problems', 'People with heart problems', 'Wheelchair users'],
        bring: ['Comfortable shoes'],
        notAllowed: ['Luggage or large bags'],
        know: ['Lunch, personal expenses, taxes, fees, handling charges and entrance fees to facilities are not included.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Qəbələ Günlük Turu',
        summary: 'Qəbələnin füsunkar təbiət mühitində gəzinti və istirahət günü: Nohur gölü və sakit suda əks olunan yüksək dağlar.',
        highlights: ['Sakit Nohur gölü kənarında dincəlin', 'Yeddi Gözəl şəlaləsini görün', 'Bir neçə dünya səviyyəli obyektdə idmanda şansınızı sınayın'],
        description: [
          'Bakıdakı otelinizdən götürülün və Qəbələyə yollanın, yolda Şamaxıda yemək və ya çay üçün fasilə olacaq. Qəbələdə hündür dağlarla əhatə olunmuş təmiz göl olan Nohur gölünə gedin. Üzmək qadağandır (göl həm də Qəbələ və ətraf rayonlar üçün içməli su təmin edir), amma balıq tutmaq üçün idealdır, qayığa minib gölü rahat gəzə bilərsiniz.',
          'Sonra çoxsaylı pillələri olan yeddi pilləli Yeddi Gözəl şəlaləsinə gedin. Dik yamacla qalxmaq təhlükəli olduğundan yalnız iki pilləni görmək mümkündür. Mövsümi restoran və çayxanada sərin kölgədə dincəlin, axan suyun səsini dinləyin.',
          'Tufandağ Qış Turizm Kompleksinə davam edin və dünyanın ən uzun kabel yoluna minin; qışda xizək sürün və ya yayda alp mənzərələrinin unudulmaz görünüşündən zövq alın. Sonra atıcılıq, boks, karate, taekvondo, futbol və cüdo üzrə peşəkar idmançılar hazırlayan dünya səviyyəli obyekt olan Qəbələ İdman Klubuna baş çəkin, milli olimpiya komandasının məşq etdiyi yerdə atıcılıqda şansınızı sınayın. Aktiv gündən sonra Bakıya qayıdın.',
        ],
        includes: ['Peşəkar bələdçi', 'Rahat sedan avtomobil', 'Otelə gəliş və qaytarılma', 'Su'],
        excludes: ['Nahar', 'Şəxsi xərclər', 'Bütün vergilər, rüsumlar və xidmət haqları', 'Obyektlərə giriş haqları'],
        notSuitable: ['Hamilə qadınlar', 'Bel problemi olanlar', 'Ürək problemi olanlar', 'Əlil arabasından istifadə edənlər'],
        bring: ['Rahat ayaqqabı'],
        notAllowed: ['Baqaj və iri çantalar'],
        know: ['Nahar, şəxsi xərclər, vergilər, rüsumlar, xidmət haqları və obyektlərə giriş haqları daxil deyil.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Однодневная поездка в Габалу',
        summary: 'День осмотра достопримечательностей и отдыха на потрясающей природе Габалы: озеро Нохур и высокие горы, отражающиеся в спокойной воде.',
        highlights: ['Отдых у безмятежного озера Нохур', 'Водопад «Семь красавиц»', 'Попробуйте себя в спорте на нескольких объектах мирового уровня'],
        description: [
          'Вас заберут из вашего отеля в Баку, и вы отправитесь в Габалу; по пути — остановка в Шемахе, чтобы перекусить или выпить чаю. В Габале вы поедете к озеру Нохур — чистому озеру в окружении высоких гор. Купаться в нём запрещено (озеро также снабжает питьевой водой Габалу и окрестности), но оно прекрасно подходит для рыбалки, а на лодке можно неспешно исследовать озеро.',
          'Затем вас ждёт водопад «Семь красавиц» — семиступенчатый водопад с множеством каскадов. Подъём по крутому склону довольно опасен, поэтому можно увидеть только два каскада. Отдохните в сезонном ресторане-чайхане в прохладной тени под шум воды.',
          'Продолжите путь на зимний курорт Туфандаг и прокатитесь на самой длинной в мире канатной дороге; зимой — лыжи, летом — незабываемые виды на альпийские ландшафты. Затем посетите спортивный клуб Габалы — объект мирового уровня, где готовят профессиональных спортсменов по стрельбе, боксу, карате, тхэквондо, футболу и дзюдо, и попробуйте стрельбу там, где тренируется олимпийская сборная. После активного дня возвращайтесь в Баку.',
        ],
        includes: ['Профессиональный гид', 'Комфортабельный седан', 'Трансфер из отеля и обратно', 'Вода'],
        excludes: ['Обед', 'Личные расходы', 'Все налоги, сборы и комиссии', 'Входные билеты на объекты'],
        notSuitable: ['Беременным женщинам', 'Людям с проблемами спины', 'Людям с проблемами сердца', 'Пользователям инвалидных колясок'],
        bring: ['Удобная обувь'],
        notAllowed: ['Багаж и большие сумки'],
        know: ['Обед, личные расходы, налоги, сборы, комиссии и входные билеты на объекты не включены.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },
];
