// Seed content, part 2: Gobustan, Lahij, Shirvan National Park and the Sheki
// tours (source: Seed_tours.pdf). Same shape and price conventions as
// seedToursBaku.js - see the header there. prices: see the header there.

export const REGIONS_A_TOURS = [
  {
    key: 'gobustan-mud-volcanoes-ateshgah',
    operator: 'Qafqaz Tours',
    location: 'Qobustan',
    category: 'nature',
    photo: '/seed/gobustan-mud-volcanoes-ateshgah.jpg',
    price: 84, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { guide_languages: ['en'], pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Gobustan Mud Volcanoes, Ateshgah and Yanardag Tour',
        summary: 'A day trip from Baku to the ancient petroglyphs of Gobustan, the unique mud volcanoes, the Ateshgah Fire Temple and the eternal flames of Yanardag.',
        highlights: ['Witness the natural eternal flames of Yanardag', 'Discover the ancient petroglyphs of Gobustan National Park', 'Experience an exciting 4×4 ride to Azerbaijan\'s unique mud volcanoes', 'Visit the historic Ateshgah Fire Temple and learn about ancient fire-worship', 'Stop at the elegant Bibi-Heybat Mosque with scenic Caspian Sea views'],
        description: [
          'Begin with an easy and comfortable pickup from your hotel or preferred location in Baku, then head out to explore the highlights of the region with a professional English-speaking guide in a comfortable air-conditioned vehicle.',
          'Discover the ancient rock art of Gobustan National Park, ride in a 4×4 to the bubbling mud volcanoes, visit the historic Ateshgah Fire Temple and watch the eternal flames burning on the hillside at Yanardag. On the way, stop at the elegant Bibi-Heybat Mosque, which overlooks the Caspian Sea.',
        ],
        includes: ['Round-trip hotel pickup and drop-off in Baku', 'Transportation in a comfortable, air-conditioned vehicle', 'Services of a professional English-speaking guide', 'All attraction entry tickets (only with the "Entrance Fees Included" option)', 'Lunch and drinks (only if selected in your package)'],
        excludes: ['Entrance fees, off-road fee and lunch are not included in the Private Tour option'],
        notSuitable: [],
        bring: ['Comfortable shoes', 'Camera', 'Weather-appropriate clothing'],
        notAllowed: [],
        know: [
          'Gobustan Rock Art Museum: 15 AZN per person.',
          'Mud volcanoes off-road 4×4 transfer: 30 AZN per person (mandatory).',
          'Ateshgah Fire Temple and Yanardag: 25 AZN per person (combined ticket).',
          'In case of rainy weather, the visit is replaced with the Mud Volcanoes Complex; the fee remains unchanged.',
          'Select the "Entrance Fees Included" option to have all tickets arranged and paid by the operator. Guests who choose the standard option can pay entrance fees on site.',
          'Accepted payment methods: cash, credit/debit card or secure payment link.',
          'For private tours, a professional guide is not included by default but can be added on request.',
          'Please provide a WhatsApp number for contact.',
        ],
        meeting: 'Round-trip hotel pickup and drop-off in Baku. Confirm your pickup address when booking.',
      },
      az: {
        title: 'Qobustan Palçıq Vulkanları, Atəşgah və Yanardağ Turu',
        summary: 'Bakıdan Qobustanın qədim qayaüstü rəsmlərinə, unikal palçıq vulkanlarına, Atəşgah məbədinə və Yanardağın əbədi alovlarına bir günlük tur.',
        highlights: ['Yanardağın təbii əbədi alovlarını görün', 'Qobustan Milli Parkının qədim qayaüstü təsvirlərini kəşf edin', 'Azərbaycanın unikal palçıq vulkanlarına həyəcanlı 4×4 səyahəti', 'Tarixi Atəşgah məbədini ziyarət edin və qədim atəşpərəstlik haqqında öyrənin', 'Xəzər dənizi mənzərəsi olan zərif Biby-Heybət məscidində dayanın'],
        description: [
          'Bakıda otelinizdən və ya istədiyiniz yerdən rahat gəlişlə başlayın, sonra peşəkar ingilisdilli bələdçi ilə kondisionerli rahat avtomobildə regionun əsas görməli yerlərini kəşf etməyə yollanın.',
          'Qobustan Milli Parkının qədim qaya rəsmlərini kəşf edin, qaynayan palçıq vulkanlarına 4×4 ilə gedin, tarixi Atəşgah məbədini ziyarət edin və Yanardağda yamacda yanan əbədi alovlara tamaşa edin. Yolda Xəzər dənizinə baxan zərif Biby-Heybət məscidində dayanacaqsınız.',
        ],
        includes: ['Bakıda otelə gəliş və qaytarılma', 'Kondisionerli rahat avtomobildə nəqliyyat', 'Peşəkar ingilisdilli bələdçi xidməti', 'Bütün giriş biletləri (yalnız "Giriş haqları daxil" seçimində)', 'Nahar və içkilər (yalnız paketdə seçilibsə)'],
        excludes: ['Şəxsi tur seçimində giriş haqları, off-road haqqı və nahar daxil deyil'],
        notSuitable: [],
        bring: ['Rahat ayaqqabı', 'Fotoaparat', 'Havaya uyğun geyim'],
        notAllowed: [],
        know: [
          'Qobustan Qayaüstü Rəsmlər Muzeyi: adambaşı 15 AZN.',
          'Palçıq vulkanlarına off-road 4×4 transfer: adambaşı 30 AZN (məcburi).',
          'Atəşgah məbədi və Yanardağ: adambaşı 25 AZN (ümumi bilet).',
          'Yağışlı havada ziyarət Palçıq Vulkanları Kompleksi ilə əvəz olunur; haqq dəyişmir.',
          'Bütün biletlərin operator tərəfindən təşkil və ödənilməsi üçün "Giriş haqları daxil" seçimini seçin. Standart seçimi seçən qonaqlar giriş haqlarını yerində ödəyə bilər.',
          'Qəbul olunan ödəniş üsulları: nağd, kredit/debet kartı və ya təhlükəsiz ödəniş linki.',
          'Şəxsi turlarda peşəkar bələdçi defolt olaraq daxil deyil, lakin sorğu ilə əlavə oluna bilər.',
          'Əlaqə üçün WhatsApp nömrəsi təqdim edin.',
        ],
        meeting: 'Bakıda otelə gəliş və qaytarılma. Gəliş ünvanını bron zamanı təsdiqləyin.',
      },
      ru: {
        title: 'Гобустан, грязевые вулканы, Атешгях и Янардаг',
        summary: 'Однодневная поездка из Баку к древним петроглифам Гобустана, уникальным грязевым вулканам, храму огнепоклонников Атешгях и вечным огням Янардага.',
        highlights: ['Вечные природные огни Янардага', 'Древние петроглифы Национального парка Гобустан', 'Захватывающая поездка на 4×4 к уникальным грязевым вулканам Азербайджана', 'Исторический храм огнепоклонников Атешгях и рассказ о древнем огнепоклонничестве', 'Остановка у изящной мечети Биби-Эйбат с видом на Каспийское море'],
        description: [
          'Начните с удобного трансфера от вашего отеля или другого места в Баку и отправляйтесь исследовать главные места региона с профессиональным англоговорящим гидом в комфортабельном автомобиле с кондиционером.',
          'Увидите древние наскальные рисунки Национального парка Гобустан, прокатитесь на 4×4 к бурлящим грязевым вулканам, посетите исторический храм Атешгях и полюбуетесь вечными огнями на склоне Янардага. По дороге вы остановитесь у изящной мечети Биби-Эйбат с видом на Каспий.',
        ],
        includes: ['Трансфер из отеля в Баку и обратно', 'Транспорт — комфортабельный автомобиль с кондиционером', 'Услуги профессионального англоговорящего гида', 'Все входные билеты (только в варианте «Входные билеты включены»)', 'Обед и напитки (только если выбраны в пакете)'],
        excludes: ['В варианте частного тура входные билеты, сбор за внедорожный трансфер и обед не включены'],
        notSuitable: [],
        bring: ['Удобная обувь', 'Фотоаппарат', 'Одежда по погоде'],
        notAllowed: [],
        know: [
          'Музей наскальных рисунков Гобустана: 15 AZN с человека.',
          'Внедорожный трансфер к грязевым вулканам на 4×4: 30 AZN с человека (обязательно).',
          'Храм Атешгях и Янардаг: 25 AZN с человека (единый билет).',
          'В дождливую погоду посещение заменяется Комплексом грязевых вулканов; стоимость остаётся прежней.',
          'Выберите вариант «Входные билеты включены», чтобы все билеты оформил и оплатил оператор. Гости со стандартным вариантом могут оплатить билеты на месте.',
          'Способы оплаты: наличные, банковская карта или безопасная ссылка на оплату.',
          'В частных турах профессиональный гид по умолчанию не включён, но может быть добавлен по запросу.',
          'Для связи необходимо указать номер WhatsApp.',
        ],
        meeting: 'Трансфер из отеля в Баку и обратно. Адрес подтверждается при бронировании.',
      },
    },
  },

  {
    key: 'lahij-village-city-of-masters',
    operator: 'Qafqaz Tours',
    location: 'İsmayıllı',
    category: 'history',
    photo: '/seed/lahij-village-city-of-masters.jpg',
    price: 65, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'guide',
    vehicle_features: null,
    facts: { pickup: true, private: false },
    route: 'Pickup point (Baku)',
    i18n: {
      en: {
        title: 'Lahij Village Tour: The City of Masters',
        summary: 'Lahij is living history, where local residents carefully keep the traditions and crafts of their ancestors to this day.',
        highlights: ['Lahij, the village of masters', 'Diri Baba Mausoleum, built on a site carved into a steep rock', 'Shamakhi, the city of Pushkin\'s fairy tales'],
        description: [
          'Lahij is a living history. Known since the Great Silk Road as an old center of copper dish production and minting, it is still famous for its craftsmen. The road to Lahij winds across picturesque mountain slopes at an altitude of 1,300 meters.',
          'The excursion begins at the Diri Baba Mausoleum, a two-story mausoleum-mosque built in 1402 on a site carved into a steep rock. Then you visit Juma Mosque in Shamakhi (8th–9th centuries), the oldest mosque in Azerbaijan and the second oldest in the Caucasus. On the way you pass vineyards, a beautiful mountain pass and a suspension bridge over a turbulent mountain river, where you stop for a walk.',
          'Lahij lies 180 km north-west of Baku. On arrival you have lunch, at your choice, at a restaurant or in a local resident\'s home. Then you walk around Lahij to see surviving smelting furnaces and workshops, an underground bath and an old mosque. Shops and workshops offer a huge assortment of local products, from small boxes to handmade samovars.',
          'On the way back, at the guests\' request, you can visit a winery and taste several types of Azerbaijani wine.',
        ],
        includes: ['Guide services', 'Transportation'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Lunch takes place at a restaurant or in a local home, at your choice.', 'A winery visit with wine tasting is available on the way back on request.'],
        meeting: 'Pickup from 1 location. Drop-off is at the same place.',
      },
      az: {
        title: 'Lahıc Kəndi Turu: Ustalar Şəhəri',
        summary: 'Lahıc canlı tarixdir: yerli sakinlər əcdadlarının ənənələrini və sənətkarlığını bu günə qədər diqqətlə qoruyurlar.',
        highlights: ['Lahıc: ustalar kəndi', 'Dik qayada oyulmuş sahədə tikilmiş Diri Baba türbəsi', 'Şamaxı: Puşkinin nağıllar şəhəri'],
        description: [
          'Lahıc canlı tarixdir. Böyük İpək Yolu dövründən mis qab istehsalı və sikkə kəsimi mərkəzi kimi tanınan bu kənd bu gün də sənətkarları ilə məşhurdur. Lahıca gedən yol dəniz səviyyəsindən 1300 metr yüksəklikdə füsunkar dağ yamaclarından keçir.',
          'Ekskursiya Diri Baba türbəsindən başlayır: bu, 1402-ci ildə dik qayada oyulmuş sahədə tikilmiş iki mərtəbəli türbə-məscid kompleksidir. Sonra Azərbaycanın ən qədim, Qafqazda isə ikinci ən qədim məscidi olan Şamaxı Cümə məscidini (VIII–IX əsrlər) ziyarət edirsiniz. Yolda üzüm bağlarından, gözəl dağ aşırımından keçir, çaylı dağ dərəsi üzərindəki asma körpüdə dayanıb gəzirsiniz.',
          'Lahıc Bakıdan 180 km şimal-qərbdə yerləşir. Çatdıqda istəyinizə görə restoranda və ya yerli sakinin evində nahar edirsiniz. Sonra Lahıcda qalmış əridici sobalara və emalatxanalara, yeraltı hamama və qədim məscidə baxırsınız. Dükanlarda və birbaşa emalatxanalarda kiçik qutulardan əl işi samovarlara qədər geniş çeşiddə yerli məhsullar təklif olunur.',
          'Geri qayıdarkən qonaqların xahişi ilə şərab zavoduna baş çəkib bir neçə Azərbaycan şərabını dada bilərsiniz.',
        ],
        includes: ['Bələdçi xidməti', 'Nəqliyyat'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Nahar seçiminizə görə restoranda və ya yerli evdə olur.', 'Geri yolda xahişlə şərab zavoduna baş çəkib dadma etmək mümkündür.'],
        meeting: '1 məntəqədən götürülmə. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Тур в деревню Лагидж — город мастеров',
        summary: 'Лагидж — живая история, где местные жители бережно хранят традиции и ремёсла предков по сей день.',
        highlights: ['Лагидж — деревня мастеров', 'Мавзолей Дири Баба, построенный на выточенной в скале площадке', 'Шемаха — город из сказок Пушкина'],
        description: [
          'Лагидж — живая история. Ещё со времён Великого шёлкового пути он известен как старый центр производства медной посуды и чеканки монет и по сей день славится мастерами. Дорога в Лагидж вьётся по живописным горным склонам на высоте 1300 метров.',
          'Экскурсия начинается у мавзолея Дири Баба — двухэтажного мавзолея-мечети 1402 года, построенного на площадке, высеченной в отвесной скале. Затем вы посетите Джума-мечеть в Шемахе (VIII–IX века) — старейшую мечеть Азербайджана и вторую по возрасту на Кавказе. По пути вас ждут виноградники, живописный горный перевал и подвесной мост через бурную горную реку, где вы остановитесь и пройдётесь.',
          'Лагидж расположен в 180 км к северо-западу от Баку. По прибытии вы пообедаете — на выбор в ресторане или в доме местного жителя. Затем пройдёте по Лагиджу, увидите сохранившиеся плавильные печи и мастерские, подземную баню и старую мечеть. В лавках и прямо в мастерских предлагают огромный выбор местных изделий — от шкатулок до самоваров ручной работы.',
          'На обратном пути по желанию гостей можно заехать на винодельню и попробовать несколько сортов азербайджанского вина.',
        ],
        includes: ['Услуги гида', 'Транспорт'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Обед проходит в ресторане или в доме местного жителя — на ваш выбор.', 'По запросу на обратном пути возможно посещение винодельни с дегустацией.'],
        meeting: 'Посадка из 1 точки. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'shirvan-eco-tour',
    operator: 'Caspian Adventures',
    location: 'Şirvan',
    category: 'entertainment',
    photo: '/seed/shirvan-eco-tour.jpg',
    price: 25, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide',
    vehicle_features: null,
    facts: { guide_languages: ['en'], pickup: true, private: false },
    route: '08:00 - Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Shirvan Eco-Tour: Gazelles, Birdwatching and Village Lunch',
        summary: 'Escape Baku on a full-day eco-tour to Shirvan National Park: spot wild gazelles just meters away, go birdwatching and have a homemade organic lunch in a local village with fruit picking.',
        highlights: ['Spot wild gazelles in Shirvan National Park with a 100% sighting guarantee', 'Enjoy birdwatching in a protected wetland area with binoculars', 'Visit Sangachal Caravanserai, a Silk Road-era landmark', 'Dine in a local home with organic Azerbaijani dishes', 'Support rural communities and conservation through sustainable travel'],
        description: [
          'Step into the wild on this eco-tour from Baku to Shirvan National Park, home to the largest population of goitered gazelles in the Caucasus. Travel in comfort to the Kur-Araz lowland, with a quick cultural stop at the historic Sangachal Caravanserai en route.',
          'Arrive early for a guided safari across the park\'s semi-desert landscapes and wetlands. Watch wild gazelles from just 5–10 meters away and enjoy immersive birdwatching with binoculars provided. Learn about the park\'s flora, fauna and conservation efforts supported by WWF and IDEA.',
          'Afterwards, enjoy authentic hospitality in a nearby local home with a fully organic Azerbaijani lunch prepared from local ingredients, followed by a relaxing walk through a grape garden where you can harvest and buy seasonal fruit.',
        ],
        includes: ['Hotel pickup and drop-off', 'Park entrance and guided safari', 'Birdwatching with equipment', 'English-speaking guide', 'Seasonal fruit-picking experience'],
        excludes: ['Homemade organic lunch (15 AZN)', 'Personal purchases (e.g. fruit)'],
        notSuitable: [],
        bring: ['Comfortable shoes'],
        notAllowed: [],
        know: [
          'The tour starts promptly at 08:00 to ensure optimal wildlife viewing.',
          'Gazelle sightings are guaranteed year-round, but bird species vary by season.',
          'The tour involves light walking on uneven ground; comfortable shoes are recommended.',
          'Fruit availability in the garden depends on the season (grapes, figs, pomegranates, etc.).',
          'This is an eco-tour: please help protect the environment by not littering or leaving the paths.',
          'A minimum of 2 participants is required for the tour to operate.',
        ],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Şirvan Eko-Turu: Ceyranlar, Quş Müşahidəsi və Kənd Naharı',
        summary: 'Bakıdan bir günlük eko-turla Şirvan Milli Parkına: vəhşi ceyranları bir neçə metrdən görün, quş müşahidəsi edin və kənddə təzə meyvə yığımı ilə ev yeməyi naharı edin.',
        highlights: ['Şirvan Milli Parkında 100% görmə zəmanəti ilə vəhşi ceyranları görün', 'Qorunan bataqlıq ərazisində dürbünlə quş müşahidəsi', 'İpək Yolu dövrünün abidəsi Səngəçal karvansarasını ziyarət edin', 'Yerli evdə üzvi Azərbaycan yeməkləri ilə nahar edin', 'Davamlı turizmlə kənd icmalarını və təbiəti mühafizə səylərini dəstəkləyin'],
        description: [
          'Bakıdan Qafqazda ən çox ceyran populyasiyasına malik Şirvan Milli Parkına bu eko-turda təbiətin qoynuna daxil olun. Kür-Araz ovalığına rahat səyahət edin, yolda tarixi Səngəçal karvansarasında qısa mədəni dayanacaq olacaq.',
          'Parkın yarımsəhra mənzərələri və bataqlıqları boyunca bələdçili safari üçün tezdən çatın. Vəhşi ceyranları cəmi 5–10 metrdən izləyin və dürbünlə quş müşahidəsindən zövq alın. Parkın florası, faunası və WWF və IDEA tərəfindən dəstəklənən mühafizə işləri haqqında öyrənin.',
          'Sonra yaxınlıqdakı yerli evdə yerli məhsullardan hazırlanmış tam üzvi Azərbaycan naharı ilə səmimi qonaqpərvərliyi yaşayın, ardınca üzüm bağında gəzin, mövsümi meyvələr yığıb ala bilərsiniz.',
        ],
        includes: ['Otelə gəliş və qaytarılma', 'Park girişi və bələdçili safari', 'Avadanlıqla quş müşahidəsi', 'İngilisdilli bələdçi', 'Mövsümi meyvə yığımı təcrübəsi'],
        excludes: ['Ev yeməyi üzvi nahar (15 AZN)', 'Şəxsi alışlar (məs. meyvə)'],
        notSuitable: [],
        bring: ['Rahat ayaqqabı'],
        notAllowed: [],
        know: [
          'Vəhşi təbiəti ən yaxşı müşahidə etmək üçün tur dəqiq saat 08:00-da başlayır.',
          'Ceyranların görünməsi ilboyu zəmanət verilir, quş növləri isə fəsildən asılı olaraq dəyişir.',
          'Tur qeyri-bərabər yerdə yüngül gəzintini əhatə edir; rahat ayaqqabı tövsiyə olunur.',
          'Bağda meyvələrin mövcudluğu fəsildən asılıdır (üzüm, əncir, nar və s.).',
          'Bu eko-turdur: zəhmət olmasa zibil atmayın və cığırlardan kənara çıxmayın.',
          'Turun keçirilməsi üçün minimum 2 iştirakçı tələb olunur.',
        ],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Эко-тур в Ширван: газели, наблюдение за птицами и обед в деревне',
        summary: 'Однодневный эко-тур из Баку в Ширванский национальный парк: дикие газели в нескольких метрах, наблюдение за птицами и домашний органический обед в деревне со сбором фруктов.',
        highlights: ['Дикие газели в Ширванском национальном парке со 100% гарантией встречи', 'Наблюдение за птицами в охраняемой водно-болотной зоне с биноклем', 'Караван-сарай Сангачал — памятник эпохи Шёлкового пути', 'Обед в местном доме с органическими азербайджанскими блюдами', 'Поддержка сельских общин и охраны природы через ответственный туризм'],
        description: [
          'Окунитесь в дикую природу на этом эко-туре из Баку в Ширванский национальный парк, где живёт самая большая на Кавказе популяция джейранов. Вы с комфортом доберётесь до Кура-Араксинской низменности, по пути сделав короткую культурную остановку у исторического караван-сарая Сангачал.',
          'Приезжайте рано на сафари с гидом по полупустынным ландшафтам и водно-болотным угодьям парка. Наблюдайте за дикими газелями с расстояния всего 5–10 метров и наслаждайтесь наблюдением за птицами — бинокли предоставляются. Узнайте о флоре и фауне парка и о природоохранной работе при поддержке WWF и IDEA.',
          'Затем вас ждёт настоящее гостеприимство в ближайшем местном доме — полностью органический азербайджанский обед из местных продуктов, а после — прогулка по винограднику, где можно собрать и купить сезонные фрукты.',
        ],
        includes: ['Трансфер из отеля и обратно', 'Вход в парк и сафари с гидом', 'Наблюдение за птицами с оборудованием', 'Англоговорящий гид', 'Сбор сезонных фруктов'],
        excludes: ['Домашний органический обед (15 AZN)', 'Личные покупки (например, фрукты)'],
        notSuitable: [],
        bring: ['Удобная обувь'],
        notAllowed: [],
        know: [
          'Экскурсия начинается ровно в 08:00 — это лучшее время для наблюдения за животными.',
          'Встреча с газелями гарантирована круглый год, а виды птиц зависят от сезона.',
          'Предстоит лёгкая прогулка по неровной местности; рекомендуется удобная обувь.',
          'Наличие фруктов в саду зависит от сезона (виноград, инжир, гранаты и т. д.).',
          'Это эко-тур: пожалуйста, не мусорите и не сходите с троп.',
          'Для проведения тура необходимо минимум 2 участника.',
        ],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'sheki-old-town-khans-palace',
    operator: 'Qafqaz Tours',
    location: 'Şəki',
    category: 'history',
    photo: '/seed/sheki-old-town-khans-palace.jpg',
    price: 38, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'breakfast,guide',
    vehicle_features: 'ac',
    facts: { guide_languages: ['en'], pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Sheki Old Town and Khan\'s Palace Experience',
        summary: 'Discover the charm of Sheki, one of Azerbaijan\'s most beautiful cities: the magnificent Khan\'s Palace, the ancient caravanserai and the atmospheric old town.',
        highlights: ['Explore the history of the region with your guide', 'Scenic drive from Baku through the Azerbaijani countryside', 'Traditional breakfast stop in Shamakhi', 'Visit the historic Sheki Khans\' Palace', 'Explore Sheki Caravanserai and local artisan shops'],
        description: [
          'Set out on a full-day adventure from Baku to the historic, picturesque city of Sheki. Travel early in the morning across the Azerbaijani countryside toward the mountains. Stop for a traditional breakfast in Shamakhi with mountain honey, Shamakhi cheese and fresh omelets, then take a tea break among towering trees in the lush Ismayilli Forests.',
          'In Sheki your first major stop is the Sheki Khans\' Palace, a masterpiece of 18th-century Azerbaijani architecture and a UNESCO-recognized highlight, with intricate stained-glass windows, ornate carvings and frescoes. You also visit the historic Sheki Caravanserai, originally a Silk Road travelers\' rest stop, with traditional shops selling local crafts, silk, jewelry and the famous Sheki halva. Explore some 18th-century shops, sample Sheki\'s renowned sweets and head up to Sheki Panoramic Park for views over the city and mountains.',
          'Enjoy lunch in the village of Kish, where you taste Sheki piti, a rich lamb stew served in a distinctive clay pot. Next visit the ancient Temple of Caucasian Albania in Kish, one of the oldest local monuments, before the scenic drive back to Baku.',
        ],
        includes: ['Professional English-speaking guide', 'Comfortable car with seat belts and air conditioning', 'All entry tickets (if the All Inclusive option is selected)', 'Breakfast and lunch (if the All Inclusive option is selected)', 'Tea break along the route'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Entry tickets, breakfast and lunch are included only with the All Inclusive option.'],
        meeting: 'Hotel pickup in Baku early in the morning. Confirm your pickup address when booking.',
      },
      az: {
        title: 'Şəki Köhnə Şəhər və Xan Sarayı Turu',
        summary: 'Azərbaycanın ən gözəl şəhərlərindən biri olan Şəkinin cazibəsini kəşf edin: möhtəşəm Xan Sarayı, qədim karvansara və atmosferik köhnə şəhər.',
        highlights: ['Bələdçi ilə regionun tarixini kəşf edin', 'Bakıdan Azərbaycan kəndləri boyunca mənzərəli yol', 'Şamaxıda ənənəvi səhər yeməyi dayanacağı', 'Tarixi Şəki Xan Sarayını ziyarət edin', 'Şəki karvansarasını və yerli sənətkar mağazalarını gəzin'],
        description: [
          'Bakıdan tarixi və füsunkar Şəki şəhərinə bir günlük macəraya çıxın. Səhər tezdən Azərbaycan kəndləri boyunca dağlara doğru səyahət edin. Şamaxıda dağ balı, Şamaxı pendiri və təzə omletlə ənənəvi səhər yeməyi edin, sonra İsmayıllı meşələrində ucaboylu ağaclar arasında çay fasiləsi verin.',
          'Şəkidə ilk əsas dayanacağınız 18-ci əsr Azərbaycan memarlığının şah əsəri və UNESCO tərəfindən tanınan Şəki Xan Sarayıdır: mürəkkəb şəbəkə pəncərələri, bəzəkli oymalar və freskalar. Eləcə də əvvəllər İpək Yolu səyyahlarının dincəlmə məntəqəsi olan tarixi Şəki karvansarasını ziyarət edirsiniz; burada yerli sənət əsərləri, ipək, zərgərlik və məşhur Şəki halvası satan ənənəvi dükanlar var. 18-ci əsrə aid dükanları gəzin, Şəkinin məşhur şirniyyatlarından dadın və şəhərin və dağların mənzərəsi üçün Şəki Panoram Parkına qalxın.',
          'Kiş kəndində nahar edin və özünəməxsus gil qabda verilən zəngin quzu yeməyi olan Şəki pitisini dadın. Sonra Kişdəki ən qədim yerli abidələrdən biri olan Qafqaz Albaniyası məbədini ziyarət edin, ardınca Bakıya mənzərəli yol.',
        ],
        includes: ['Peşəkar ingilisdilli bələdçi', 'Təhlükəsizlik kəmərli və kondisionerli rahat avtomobil', 'Bütün giriş biletləri ("Hər şey daxil" seçimində)', 'Səhər yeməyi və nahar ("Hər şey daxil" seçimində)', 'Marşrut boyu çay fasiləsi'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Giriş biletləri, səhər yeməyi və nahar yalnız "Hər şey daxil" seçimində daxildir.'],
        meeting: 'Səhər tezdən Bakıda otelə gəliş. Gəliş ünvanını bron zamanı təsdiqləyin.',
      },
      ru: {
        title: 'Старый город Шеки и Дворец шекинских ханов',
        summary: 'Откройте для себя очарование Шеки — одного из самых красивых городов Азербайджана: великолепный Дворец ханов, древний караван-сарай и атмосферный старый город.',
        highlights: ['История региона вместе с гидом', 'Живописная дорога из Баку через азербайджанскую глубинку', 'Традиционный завтрак в Шемахе', 'Исторический Дворец шекинских ханов', 'Шекинский караван-сарай и лавки местных мастеров'],
        description: [
          'Отправьтесь в однодневное путешествие из Баку в исторический живописный город Шеки. Рано утром вы поедете через азербайджанскую глубинку к горам. По пути — традиционный завтрак в Шемахе с горным мёдом, шемахинским сыром и свежими омлетами, а затем чайная пауза среди высоких деревьев в живописных Исмаиллинских лесах.',
          'В Шеки первая главная остановка — Дворец шекинских ханов, шедевр азербайджанской архитектуры XVIII века, признанный ЮНЕСКО: витражи-шебеке, резьба и фрески. Вы также посетите исторический Шекинский караван-сарай, когда-то место отдыха путников Шёлкового пути, а сегодня — лавки с местными ремёслами, шёлком, украшениями и знаменитой шекинской халвой. Зайдите в лавки XVIII века, попробуйте прославленные шекинские сладости и поднимитесь в Панорамный парк Шеки с видами на город и горы.',
          'Пообедайте в деревне Киш и попробуйте шекинский пити — наваристое блюдо из баранины в характерном глиняном горшочке. Затем посетите древний храм Кавказской Албании в Кише — один из старейших местных памятников — и отправляйтесь по живописной дороге обратно в Баку.',
        ],
        includes: ['Профессиональный англоговорящий гид', 'Комфортабельный автомобиль с ремнями безопасности и кондиционером', 'Все входные билеты (при выборе варианта «Всё включено»)', 'Завтрак и обед (при выборе варианта «Всё включено»)', 'Чайная пауза по пути'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Входные билеты, завтрак и обед включены только в варианте «Всё включено».'],
        meeting: 'Трансфер из отеля в Баку рано утром. Адрес подтверждается при бронировании.',
      },
    },
  },

  {
    key: 'sheki-old-town-walking',
    operator: 'Qafqaz Tours',
    location: 'Şəki',
    category: 'entertainment',
    photo: '/seed/sheki-old-town-walking.jpg',
    price: 56, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'guide',
    vehicle_features: null,
    facts: { pickup: false, private: false },
    route: 'Khan\'s Palace, Sheki',
    i18n: {
      en: {
        title: 'Sheki Old Town Walking Tour',
        summary: 'Discover the charm of Sheki\'s Old Town on a guided walking tour through its historic streets, ancient caravanserai and traditional craft workshops.',
        highlights: ['Sheki, the unsung culture capital', 'UNESCO World Heritage', 'History and cultural places'],
        description: [
          'Discover the rich history, architecture and traditional craftsmanship of Sheki on a guided walk through the heart of the Old Town, perfect for culture lovers and curious travelers.',
          'Begin at the magnificent Khan\'s Palace, an 18th-century masterpiece with flawless stained-glass shebeke windows, colorful frescoes and ornate wooden carvings. Continue to the Ceramic House to see traditional pottery techniques, then to the impressive Round Temple, a structure with layers of multicultural heritage, and the History and Ethnographic Museum with its collections on Sheki\'s archaeology, daily life, crafts and Silk Road connections.',
          'Visit the Craftsmen House, where artisans create handmade shebeke, copperwork and embroidery, step inside the historic Upper Caravanserai, once an important resting place for Silk Road merchants, and stop by the Khan\'s Mosque. Finish in the lively local bazaars, where vendors sell fresh produce, sweets, spices and handmade goods.',
        ],
        includes: ['Live tour guide'],
        excludes: ['Meal', 'Water', 'Entrance tickets'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Entrance tickets to the sites are paid separately.'],
        meeting: 'The tour begins at the Khan\'s Palace in Sheki.',
      },
      az: {
        title: 'Şəki Köhnə Şəhər Piyada Turu',
        summary: 'Bələdçili piyada turda Şəkinin Köhnə Şəhərini kəşf edin: tarixi küçələr, qədim karvansara və ənənəvi sənətkarlıq emalatxanaları.',
        highlights: ['Şəki: mədəniyyətin tanınmayan paytaxtı', 'UNESCO Ümumdünya İrsi', 'Tarix və mədəniyyət məkanları'],
        description: [
          'Köhnə Şəhərin mərkəzindən keçən bələdçili gəzintidə Şəkinin zəngin tarixini, memarlığını və ənənəvi sənətkarlığını kəşf edin: mədəniyyət həvəskarları və maraqlı səyyahlar üçün idealdır.',
          'Turu 18-ci əsr şah əsəri olan möhtəşəm Xan Sarayından başlayın: qüsursuz şəbəkə vitrajları, rəngarəng freskalar və bəzəkli taxta oymalar. Ənənəvi dulus üsullarını görmək üçün Keramika Evinə, sonra çoxmədəniyyətli irs qatlarına malik təsirli Dəyirmi Məbədə və Şəkinin arxeologiyası, məişəti, sənətkarlığı və İpək Yolu əlaqələri haqqında kolleksiyalarla zəngin Tarix-Etnoqrafiya Muzeyinə keçin.',
          'Sənətkarların əl işi şəbəkə, mis məmulatı və tikmə hazırladığı Sənətkarlar Evinə baş çəkin, İpək Yolu taciriləri üçün mühüm dincəlmə yeri olmuş tarixi Yuxarı Karvansaraya daxil olun və Xan Məscidində dayanın. Təzə məhsul, şirniyyat, ədviyyat və əl işləri satılan canlı yerli bazarlarda yekunlaşdırın.',
        ],
        includes: ['Canlı tur bələdçisi'],
        excludes: ['Yemək', 'Su', 'Giriş biletləri'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Məkanlara giriş biletləri ayrıca ödənilir.'],
        meeting: 'Tur Şəkidə Xan Sarayından başlayır.',
      },
      ru: {
        title: 'Пешая экскурсия по старому городу Шеки',
        summary: 'Откройте очарование старого города Шеки на пешей экскурсии с гидом по историческим улицам, древнему караван-сараю и традиционным мастерским.',
        highlights: ['Шеки — недооценённая культурная столица', 'Всемирное наследие ЮНЕСКО', 'История и культурные места'],
        description: [
          'Познакомьтесь с богатой историей, архитектурой и традиционными ремёслами Шеки на пешей экскурсии с гидом по сердцу старого города — идеально для любителей культуры и любознательных путешественников.',
          'Начните с великолепного Дворца ханов — шедевра XVIII века с безупречными витражами-шебеке, яркими фресками и резным деревом. Затем отправляйтесь в Дом керамики, где можно увидеть традиционные гончарные приёмы, к впечатляющему Круглому храму — зданию со слоями разных культур — и в Историко-этнографический музей с коллекциями по археологии, быту, ремёслам и связям Шёлкового пути.',
          'Загляните в Дом мастеров, где ремесленники создают шебеке, медные изделия и вышивку, зайдите в исторический Верхний караван-сарай — важное место отдыха купцов Шёлкового пути — и посетите Ханскую мечеть. Завершите прогулку на оживлённых местных базарах со свежими продуктами, сладостями, специями и изделиями ручной работы.',
        ],
        includes: ['Живой гид'],
        excludes: ['Питание', 'Вода', 'Входные билеты'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Входные билеты в достопримечательности оплачиваются отдельно.'],
        meeting: 'Экскурсия начинается у Дворца ханов в Шеки.',
      },
    },
  },

  {
    key: 'sheki-private-unesco',
    operator: 'Qafqaz Tours',
    location: 'Şəki',
    category: 'history',
    photo: '/seed/sheki-private-unesco.jpg',
    price: 44, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 1,
    max_participants: 6,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { pickup: true, private: true },
    route: 'Hotel pickup (Baku city area)',
    i18n: {
      en: {
        title: 'Sheki Private Tour: Extraordinary UNESCO Heritage',
        summary: 'Discover the beauty of Sheki on a scenic private day trip: the stunning Palace of the Sheki Khans, historic caravanserais and local sweets in a charming mountain city.',
        highlights: ['Sheki Khans\' Palace, a World Heritage site', 'The Silk Road: a time machine', 'Enjoy a traditional meal and try Sheki halva', 'The caravanserai: a time machine'],
        description: [
          'Discover the magic of Sheki on an unforgettable full-day journey through history, culture and mountain landscapes. As you travel from Baku toward the northwest, watch the scenery transform into rolling green hills, quiet mountain villages and winding roads.',
          'Your adventure begins at the Palace of the Sheki Khans, with dazzling stained-glass windows, carved wooden doors and colorful frescoes. Wander through the ancient caravanserai, once a bustling stop for Silk Road traders, with its stone arches and hidden courtyards.',
          'Feel the local rhythm at Sheki\'s traditional bazaar, taste the famous Sheki halva and enjoy a warm Azerbaijani lunch at a local restaurant with mountain views. In the afternoon visit the Juma Mosque and nearby artisan workshops, where masters still create silk and pottery using centuries-old techniques, and take a last look at Sheki\'s peaceful streets and wooden balconies before heading back.',
        ],
        includes: ['Professional tour guide', 'Professional driver assistance', 'Hotel pickup', 'Drop-off (Baku city area)', 'Comfortable vehicle with A/C'],
        excludes: ['Personal expenses'],
        notSuitable: ['People over 95 years'],
        bring: ['Comfortable shoes', 'Comfortable clothes'],
        notAllowed: ['Luggage or large bags'],
        know: ['Have a good breakfast for this long day trip.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Şəki Şəxsi Turu: Qeyri-adi UNESCO İrsi',
        summary: 'Mənzərəli şəxsi bir günlük turla Şəkinin gözəlliyini kəşf edin: füsunkar dağ şəhərində möhtəşəm Şəki Xan Sarayı, tarixi karvansaralar və yerli şirniyyatlar.',
        highlights: ['Şəki Xan Sarayı: Ümumdünya İrsi', 'İpək Yolu: zaman maşını', 'Ənənəvi yemək və Şəki halvası dadı', 'Karvansara: zaman maşını'],
        description: [
          'Tarix, mədəniyyət və dağ mənzərələri ilə dolu unudulmaz bir günlük səyahətdə Şəkinin sehrini kəşf edin. Bakıdan şimal-qərbə doğru gedərkən mənzərənin dalğalı yaşıl təpələrə, sakit dağ kəndlərinə və qıvrım yollara çevrilməsini izləyin.',
          'Macəranız parlaq şəbəkə pəncərələri, oyma taxta qapıları və rəngarəng freskaları ilə şah əsəri olan Şəki Xan Sarayından başlayır. Daş tağları və gizli həyətləri ilə İpək Yolu taciriləri üçün şən dayanacaq olmuş qədim karvansaranı gəzin.',
          'Şəkinin ənənəvi bazarında yerli ritmi hiss edin, məşhur Şəki halvasını dadın və dağ mənzərəli yerli restoranda isti Azərbaycan naharı edin. Günortadan sonra Cümə Məscidini və ustaların hələ də əsrlik üsullarla ipək və saxsı hazırladığı yaxınlıqdakı sənətkar emalatxanalarını ziyarət edin, geri dönməzdən əvvəl Şəkinin sakit küçələrinə və taxta eyvanlarına son dəfə baxın.',
        ],
        includes: ['Peşəkar tur bələdçisi', 'Peşəkar sürücü xidməti', 'Otelə gəliş', 'Qaytarılma (Bakı şəhəri daxilində)', 'Kondisionerli rahat avtomobil'],
        excludes: ['Şəxsi xərclər'],
        notSuitable: ['95 yaşdan yuxarı şəxslər'],
        bring: ['Rahat ayaqqabı', 'Rahat geyim'],
        notAllowed: ['Baqaj və iri çantalar'],
        know: ['Bu uzun günlük səfər üçün yaxşı səhər yeməyi edin.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Частный тур в Шеки: исключительное наследие ЮНЕСКО',
        summary: 'Откройте красоту Шеки на живописной частной однодневной поездке: потрясающий Дворец шекинских ханов, исторические караван-сараи и местные сладости в очаровательном горном городе.',
        highlights: ['Дворец шекинских ханов — объект всемирного наследия', 'Шёлковый путь: машина времени', 'Традиционный обед и шекинская халва', 'Караван-сарай: машина времени'],
        description: [
          'Откройте для себя магию Шеки в незабываемом однодневном путешествии по истории, культуре и горным пейзажам. По дороге из Баку на северо-запад вы увидите, как пейзаж превращается в зелёные холмы, тихие горные деревни и извилистые дороги.',
          'Приключение начинается во Дворце шекинских ханов: ослепительные витражи, резные деревянные двери и яркие фрески. Пройдитесь по древнему караван-сараю, некогда шумной стоянке купцов Шёлкового пути, с каменными арками и скрытыми двориками.',
          'Почувствуйте местный ритм на традиционном базаре Шеки, попробуйте знаменитую шекинскую халву и пообедайте в местном ресторане с видом на горы. После обеда посетите Джума-мечеть и соседние мастерские, где мастера по-прежнему делают шёлк и керамику вековыми методами, и в последний раз взгляните на тихие улочки Шеки и деревянные балконы перед возвращением.',
        ],
        includes: ['Профессиональный гид', 'Услуги профессионального водителя', 'Трансфер из отеля', 'Возвращение (в пределах Баку)', 'Комфортабельный автомобиль с кондиционером'],
        excludes: ['Личные расходы'],
        notSuitable: ['Людям старше 95 лет'],
        bring: ['Удобная обувь', 'Удобная одежда'],
        notAllowed: ['Багаж и большие сумки'],
        know: ['Хорошо позавтракайте перед этой долгой поездкой.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'sheki-sparkling-wine-2day',
    operator: 'Qafqaz Tours',
    location: 'Şəki',
    category: 'food',
    photo: '/seed/sheki-sparkling-wine-2day.jpg',
    price: 80, // AZN per person, as listed on GetYourGuide
    duration_days: 2,
    min_participants: 2,
    max_participants: 8,
    features: 'breakfast,guide,hotel_stay',
    vehicle_features: 'ac',
    facts: { pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Sparkling Wine Tour to Sheki with All Meals Included',
        summary: 'A two-day adventure from Baku to Sheki with a stop at a winery: a guided tasting of local wines, including the legendary Agdam port, and the charming city of Sheki.',
        highlights: ['Discover the sophisticated world of Azerbaijani sparkling wines at a winery', 'Enjoy a guided tasting of local wines, including the legendary Agdam port', 'Savor a delicious local lunch and a traditional tea break with baklava', 'Explore the charming city of Sheki and visit the iconic Sheki Khan\'s Palace', 'Immerse yourself in the rich history and flavors of Azerbaijan'],
        description: [
          'Combine the rich culture of Sheki with the sophistication of sparkling wine. Start with a scenic drive from Baku, stopping for a traditional tea break with local baklava, then continue to Sheki, where you enjoy a local lunch before visiting the winery.',
          'The winery, a member of the "Abrau-Durso" family since 2021, has modernized winemaking in this ancient wine region. Famous for sparkling wines made by both the Méthode Classique and Charmat methods, it produces blends like Az Abrau, local grape varietals and even the legendary Agdam port. Enjoy a guided tasting of these wines.',
          'After the winery, check in to your hotel in Sheki, enjoy dinner and visit a local wine house to sample wines from other Azerbaijani producers.',
          'On day two, have breakfast at the hotel and visit the iconic Sheki Khan\'s Palace. On the way back to Baku, stop for a relaxing lunch to conclude the tour.',
        ],
        includes: ['Transportation (minivan)', 'Pickup and drop-off', 'Guide', 'Snacks', '2 lunches, 1 dinner and 1 breakfast', 'Accommodation', 'Cheese plate', 'Tea break with local baklava', 'Entrance fee to Sheki Khans\' Palace', 'Entrance and tour of the winery', 'Wine tasting: 2 sparkling, 1 red, 1 white and a port-style dessert wine', 'Wine tasting at a wine house: 5 wines'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Visitors must be at least 18 years old.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Şəkiyə Köpüklü Şərab Turu (Bütün Yeməklər Daxil)',
        summary: 'Bakıdan Şəkiyə iki günlük macəra, şərab zavodunda dayanacaqla: yerli şərabların, o cümlədən əfsanəvi Ağdam portunun bələdçili dadılması və füsunkar Şəki şəhəri.',
        highlights: ['Şərab zavodunda Azərbaycan köpüklü şərablarının nəfis dünyasını kəşf edin', 'Yerli şərabların, o cümlədən əfsanəvi Ağdam portunun bələdçili dadılması', 'Ləzzətli yerli nahar və paxlava ilə ənənəvi çay fasiləsi', 'Füsunkar Şəki şəhərini kəşf edin və məşhur Şəki Xan Sarayını ziyarət edin', 'Azərbaycanın zəngin tarixinə və dadlarına qərq olun'],
        description: [
          'Şəkinin zəngin mədəniyyətini köpüklü şərabın zərifliyi ilə birləşdirin. Bakıdan mənzərəli yolla başlayın, yerli paxlava ilə ənənəvi çay fasiləsi verin, sonra Şəkiyə davam edin və şərab zavoduna baş çəkməzdən əvvəl yerli nahar edin.',
          '2021-ci ildən "Abrau-Dürso" ailəsinin üzvü olan şərab zavodu bu qədim şərab regionunda şərabçılığı müasirləşdirib. Həm Méthode Classique, həm də Charmat üsulu ilə hazırlanan köpüklü şərabları ilə məşhur olan zavod Az Abrau kimi blendlər, yerli Azərbaycan üzüm sortları və hətta əfsanəvi Ağdam portu istehsal edir. Bu şərabların bələdçili dadılmasından zövq alın.',
          'Şərab zavodundan sonra Şəkidə otelə yerləşin, şam yeməyi edin və digər Azərbaycan istehsalçılarının şərablarını dadmaq üçün yerli şərab evinə baş çəkin.',
          'İkinci gün otel səhər yeməyindən sonra məşhur Şəki Xan Sarayını ziyarət edin. Bakıya qayıdarkən turu tamamlamaq üçün rahat nahar fasiləsi verin.',
        ],
        includes: ['Nəqliyyat (minivan)', 'Gəliş və qaytarılma', 'Bələdçi', 'Qəlyanaltılar', '2 nahar, 1 şam və 1 səhər yeməyi', 'Yerləşmə', 'Pendir boşqabı', 'Yerli paxlava ilə çay fasiləsi', 'Şəki Xan Sarayına giriş haqqı', 'Şərab zavoduna giriş və tur', 'Şərab dadma: 2 köpüklü, 1 qırmızı, 1 ağ və port tipli desert şərabı', 'Şərab evində dadma: 5 şərab'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Ziyarətçilər ən azı 18 yaşında olmalıdır.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Тур в Шеки с дегустацией игристых вин (все приёмы пищи включены)',
        summary: 'Двухдневное приключение из Баку в Шеки с остановкой на винодельне: экскурсия с дегустацией местных вин, включая легендарный агдамский портвейн, и очаровательный город Шеки.',
        highlights: ['Изысканный мир азербайджанских игристых вин на винодельне', 'Дегустация местных вин с гидом, включая легендарный агдамский портвейн', 'Вкусный местный обед и традиционная чайная пауза с пахлавой', 'Очаровательный город Шеки и знаменитый Дворец шекинских ханов', 'Погружение в богатую историю и вкусы Азербайджана'],
        description: [
          'Соедините богатую культуру Шеки с изысканностью игристых вин. Начните с живописной дороги из Баку и остановитесь на традиционный чай с местной пахлавой, затем продолжите путь в Шеки, где перед визитом на винодельню вас ждёт местный обед.',
          'Винодельня, с 2021 года входящая в семью «Абрау-Дюрсо», модернизировала виноделие в этом древнем винодельческом регионе. Она знаменита игристыми винами, сделанными методом Méthode Classique и Charmat, и производит купажи вроде Az Abrau, вина из местных сортов винограда и даже легендарный агдамский портвейн. Вас ждёт дегустация этих вин с гидом.',
          'После винодельни вы заселитесь в отель в Шеки, поужинаете и посетите местный винный дом, где попробуете вина других азербайджанских производителей.',
          'На второй день после завтрака в отеле вы посетите знаменитый Дворец шекинских ханов. На обратном пути в Баку остановитесь на неспешный обед, который завершит это путешествие.',
        ],
        includes: ['Транспорт (микроавтобус)', 'Трансфер из отеля и обратно', 'Гид', 'Закуски', '2 обеда, 1 ужин и 1 завтрак', 'Проживание', 'Сырная тарелка', 'Чайная пауза с местной пахлавой', 'Входной билет во Дворец шекинских ханов', 'Вход и экскурсия по винодельне', 'Дегустация вин: 2 игристых, 1 красное, 1 белое и десертное вино типа портвейн', 'Дегустация в винном доме: 5 вин'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Посетители должны быть старше 18 лет.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },
];
