// Seed content, part 1: the nine Baku city tours (source: Seed_tours.pdf).
//
// Every tour carries its text in all three app languages under `i18n`:
//   title        card / page title
//   summary      one-to-two sentence teaser (cards, search, meta description)
//   highlights   short bullet list
//   description  full description, one string per paragraph
//   includes / excludes          shown with a check / cross
//   notSuitable, bring, notAllowed, know   the "important information" blocks
//   meeting      meeting point or pickup information (plain text)
// Language-neutral facts (duration in hours, guide languages...) live in `facts`.
//
// PRICES are in AZN, per person - the price listed for each tour on its GetYourGuide page.

export const BAKU_TOURS = [
  {
    key: 'baku-old-city',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'history',
    photo: '/seed/baku-old-city.jpg',
    price: 24, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { duration_hours: 4, guide_languages: ['en', 'tr'], pickup: true, private: true },
    route: 'Fountain Square',
    i18n: {
      en: {
        title: 'Baku Old City Tour',
        summary: 'A Baku city tour starting from the Old City, loved by locals and tourists alike, covering the main historical attractions of the capital.',
        highlights: ['See the Palace of the Shirvanshahs', 'Tour around Icheri Sheher, the Old City', 'Explore Baku Boulevard'],
        description: [
          'Your walking tour begins at Fountain Square, a public gathering place that is especially lively after business hours and at weekends. It is full of boutiques, restaurants, shops and hotels, and is a great spot for people-watching. The city also holds many of its public festivals and celebrations here.',
          'From here you move on to the Palace of the Shirvanshahs, a 15th-century palace that UNESCO describes as "one of the pearls of Azerbaijan\'s architecture". Together with the Maiden Tower it forms an ensemble of historic monuments on the UNESCO World Heritage List. Nearby you can browse souvenir stores, carpet shops, antique dealers and local handicraft markets.',
          'The tour then continues into Icheri Sheher, the Old City and historical core of Baku, surrounded by walls. In December 2000 it became the first location in Azerbaijan to be classified as a UNESCO World Heritage Site.',
        ],
        includes: ['Professional guide', 'Comfortable sedan throughout the tour', 'Hotel pickup and drop-off', 'Water for group members during the whole tour'],
        excludes: ['Lunch', 'Personal expenses', 'All taxes, fees and handling charges', 'Entrance fees to museums'],
        notSuitable: ['Pregnant women', 'People with back problems', 'People with heart problems', 'Wheelchair users'],
        bring: ['Comfortable shoes'],
        notAllowed: ['Luggage or large bags'],
        know: ['This tour takes place rain or shine.', 'The walking part of the tour is about 2 hours, in the Old City only.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Bakı Köhnə Şəhər Turu',
        summary: 'Yerlilərin və turistlərin sevdiyi Köhnə Şəhərdən başlayan Bakı şəhər turu: paytaxtın əsas tarixi görməli yerləri.',
        highlights: ['Şirvanşahlar Sarayını görün', 'İçərişəhəri gəzin', 'Bakı Bulvarını kəşf edin'],
        description: [
          'Piyada turunuz Fəvvarələr meydanından başlayır. Bu, iş saatlarından sonra və həftə sonları xüsusilə canlı olan ictimai toplaşma məkanıdır; butiklər, restoranlar, mağazalar və otellərlə doludur, insan seyri üçün də əladır. Şəhər bayramlarının və tədbirlərinin çoxu da məhz burada keçirilir.',
          'Buradan 15-ci əsrə aid Şirvanşahlar Sarayına keçirsiniz. UNESCO bu sarayı "Azərbaycan memarlığının incilərindən biri" kimi səciyyələndirir; Qız Qalası ilə birlikdə UNESCO-nun Ümumdünya İrsi Siyahısına daxil edilmiş tarixi abidələr ansamblını təşkil edir. Yaxınlıqda suvenir mağazalarına, xalça dükanlarına, antikvar satıcılarına və yerli əl işləri bazarlarına baş çəkə bilərsiniz.',
          'Daha sonra tur Bakının tarixi özəyi olan, qala divarları ilə əhatə olunmuş İçərişəhərə yönəlir. 2000-ci ilin dekabrında İçərişəhər Azərbaycanda UNESCO-nun Ümumdünya İrsi Siyahısına salınan ilk yer oldu.',
        ],
        includes: ['Peşəkar bələdçi', 'Tur boyu rahat sedan avtomobil', 'Otelə gəliş və otelə qaytarılma', 'Tur boyu qrup üzvləri üçün su'],
        excludes: ['Nahar', 'Şəxsi xərclər', 'Bütün vergilər, rüsumlar və xidmət haqları', 'Muzeylərə giriş haqqı'],
        notSuitable: ['Hamilə qadınlar', 'Bel problemi olanlar', 'Ürək problemi olanlar', 'Əlil arabasından istifadə edənlər'],
        bring: ['Rahat ayaqqabı'],
        notAllowed: ['Baqaj və iri çantalar'],
        know: ['Tur yağışlı və ya günəşli havadan asılı olmayaraq keçirilir.', 'Piyada hissə təxminən 2 saatdır və yalnız İçərişəhərdə baş tutur.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Обзорная экскурсия по Старому городу Баку',
        summary: 'Экскурсия по Баку, начинающаяся в Старом городе, который любят и местные жители, и туристы: главные исторические достопримечательности столицы.',
        highlights: ['Посетите Дворец Ширваншахов', 'Прогуляйтесь по Ичери-шехер', 'Откройте для себя Бакинский бульвар'],
        description: [
          'Пешеходная экскурсия начинается на площади Фонтанов — любимом месте встреч, особенно оживлённом по вечерам и в выходные. Здесь множество бутиков, ресторанов, магазинов и отелей, а ещё это отличное место, чтобы понаблюдать за жизнью города. Именно здесь проходят и многие городские праздники.',
          'Далее вы отправитесь во Дворец Ширваншахов XV века, который ЮНЕСКО называет «одной из жемчужин архитектуры Азербайджана». Вместе с Девичьей башней он входит в ансамбль памятников Списка всемирного наследия ЮНЕСКО. Рядом можно заглянуть в сувенирные лавки, ковровые магазины, антикварные лавки и рынки ремёсел.',
          'Затем маршрут ведёт в Ичери-шехер — исторический центр Баку, окружённый крепостными стенами. В декабре 2000 года он стал первым объектом в Азербайджане, внесённым в список всемирного наследия ЮНЕСКО.',
        ],
        includes: ['Профессиональный гид', 'Комфортабельный седан на протяжении всей экскурсии', 'Трансфер из отеля и обратно', 'Вода для участников группы'],
        excludes: ['Обед', 'Личные расходы', 'Все налоги, сборы и комиссии', 'Входные билеты в музеи'],
        notSuitable: ['Беременным женщинам', 'Людям с проблемами спины', 'Людям с проблемами сердца', 'Пользователям инвалидных колясок'],
        bring: ['Удобная обувь'],
        notAllowed: ['Багаж и большие сумки'],
        know: ['Экскурсия проходит в любую погоду.', 'Пешая часть длится около 2 часов и проходит только по Старому городу.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'baku-restaurant-evening',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'food',
    photo: '/seed/baku-restaurant-evening.jpg',
    price: 60, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: '',
    vehicle_features: null,
    facts: { pickup: false, private: false },
    route: 'Nizami Mall, Səlatın Əsgərova',
    i18n: {
      en: {
        title: 'Azerbaijani Restaurant Evening with Cultural Shows',
        summary: 'Experience the authentic spirit of Azerbaijan at one of Baku\'s top-rated traditional restaurants, with live music, a spectacular dance performance and a vibrant atmosphere of national culture.',
        highlights: ['Enjoy an evening at one of Baku\'s top traditional restaurants', 'Live Azerbaijani music and a spectacular folk dance show', 'Immerse yourself in rich national traditions and a vibrant atmosphere', 'Capture memorable moments during your experience', 'Freedom to choose and order dishes from the à la carte menu'],
        description: [
          'Experience the vibrant culture and hospitality of Azerbaijan during an unforgettable evening at one of Baku\'s top traditional restaurants.',
          'Step into a warm and welcoming atmosphere where rich traditions, delicious cuisine, live music and folk dance come together. You choose and order your dishes from the à la carte menu.',
        ],
        includes: ['Reservation at the restaurant', 'Traditional Azerbaijani music performance', 'Traditional Azerbaijani dance performance', 'Authentic cultural atmosphere', 'Azerbaijani hospitality experience', 'Welcome drinks'],
        excludes: ['Food', 'Hotel pickup and drop-off', 'Personal expenses'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Food is ordered and paid for separately from the à la carte menu.'],
        meeting: 'Nizami Mall, Salatyn Asgarova, Baku AZ1009.',
      },
      az: {
        title: 'Mədəni Şou Proqramlı Azərbaycan Restoranı Axşamı',
        summary: 'Bakının ən yüksək reytinqli ənənəvi restoranlarından birində canlı musiqi, möhtəşəm rəqs nömrələri və milli mədəniyyət atmosferi ilə Azərbaycanın əsl ruhunu yaşayın.',
        highlights: ['Bakının ən yaxşı ənənəvi restoranlarından birində axşam keçirin', 'Canlı Azərbaycan musiqisi və möhtəşəm xalq rəqsi şousu', 'Zəngin milli ənənələrə və canlı atmosferə qərq olun', 'Unudulmaz anları şəkilə çəkin', 'Yeməkləri à la carte menyudan sərbəst seçib sifariş edin'],
        description: [
          'Bakının ən yaxşı ənənəvi restoranlarından birində keçirəcəyiniz unudulmaz axşamda Azərbaycanın canlı mədəniyyətini və qonaqpərvərliyini yaşayın.',
          'Zəngin ənənələrin, ləziz mətbəxin, canlı musiqinin və xalq rəqslərinin birləşdiyi isti və səmimi mühitə qədəm qoyun. Yeməkləri à la carte menyudan özünüz seçib sifariş edirsiniz.',
        ],
        includes: ['Restoranda rezervasiya', 'Ənənəvi Azərbaycan musiqisi ifası', 'Ənənəvi Azərbaycan rəqsi ifası', 'Əsl mədəni atmosfer', 'Azərbaycan qonaqpərvərliyi', 'Qarşılama içkiləri'],
        excludes: ['Yemək', 'Otelə gəliş və qaytarılma', 'Şəxsi xərclər'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Yeməklər à la carte menyudan ayrıca sifariş olunur və ayrıca ödənilir.'],
        meeting: 'Nizami Mall, Səlatın Əsgərova küç., Bakı AZ1009.',
      },
      ru: {
        title: 'Вечер в азербайджанском ресторане с культурной программой',
        summary: 'Почувствуйте настоящий дух Азербайджана в одном из лучших традиционных ресторанов Баку: живая музыка, зрелищные танцы и атмосфера национальной культуры.',
        highlights: ['Вечер в одном из лучших традиционных ресторанов Баку', 'Живая азербайджанская музыка и зрелищное шоу народных танцев', 'Погружение в богатые национальные традиции и яркую атмосферу', 'Памятные моменты для фото и видео', 'Блюда можно свободно выбирать из меню à la carte'],
        description: [
          'Познакомьтесь с яркой культурой и гостеприимством Азербайджана за незабываемым вечером в одном из лучших традиционных ресторанов Баку.',
          'Окунитесь в тёплую, радушную атмосферу, где соединяются богатые традиции, вкусная кухня, живая музыка и народные танцы. Блюда вы выбираете и заказываете сами из меню à la carte.',
        ],
        includes: ['Бронирование столика в ресторане', 'Выступление традиционной азербайджанской музыки', 'Выступление традиционных азербайджанских танцев', 'Подлинная культурная атмосфера', 'Азербайджанское гостеприимство', 'Приветственные напитки'],
        excludes: ['Еда', 'Трансфер из отеля и обратно', 'Личные расходы'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Блюда заказываются и оплачиваются отдельно из меню à la carte.'],
        meeting: 'Nizami Mall, ул. Салатына Аскерова, Баку AZ1009.',
      },
    },
  },

  {
    key: 'baku-caspian-boat',
    operator: 'Caspian Adventures',
    location: 'Bakı',
    category: 'entertainment',
    photo: '/seed/baku-caspian-boat.jpg',
    price: 20, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 10,
    features: 'evening_tea',
    vehicle_features: null,
    facts: { pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Caspian Sea Boat Tour with City Skyline Views',
        summary: 'Discover Baku\'s bay on a romantic boat tour and see both historic and modern buildings from the water, at sunset or under the city lights.',
        highlights: ['Marvel at the illuminated Crystal Hall and Flame Towers', 'Enjoy fantastic views of the Baku skyline', 'Take a leisurely cruise along the coast and soak up the romantic views', 'Travel in style on one of the most elegant and modern cruises in Baku', 'Luxury relaxation in business class (depending on the option chosen)'],
        description: [
          'Discover Baku\'s bay with a romantic boat tour. See both historic and modern buildings, with different views depending on the time of day. Sit back, relax and enjoy the calm journey on the Caspian Sea.',
          'Admire the skyline from an entirely new perspective: the Tele Tower, the historic Maiden Tower and the Flame Towers, which won an award for the world\'s best-lit building in 2014. You will also see some of the largest malls in the Caucasus, including Crescent Mall, the Sea Mall and the Baku Eye.',
          'Head to the open deck for views of the illuminated Crystal Hall or, depending on departure time, the illuminated monuments between Flag Square and the Crescent Building. You will also see the world\'s largest flag, standing 72 meters high. With the business-class option you get comfortable seating and free Azerbaijani tea.',
          'Soothing music plays from the back of the boat. Please note that on days with strong winds the tour time may be adjusted.',
        ],
        includes: ['Hotel pickup and drop-off', 'Admission tickets', 'Business-class seating (optional)', 'Free Azerbaijani tea', 'Views of the Tele Tower, Maiden Tower, Flame Towers, Crescent Mall, Sea Mall, Baku Eye, Crystal Hall, Flag Square and Crescent Building', 'View of the world\'s largest flag', 'Soothing music', 'Meals and drinks are available to buy from the boat restaurant'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: ['Alcohol and drugs'],
        know: [
          'The tour time may be adjusted on days with strong winds. As wind usually picks up in the evening, the 18:30 and 20:30 departures may be moved 1–2 hours earlier.',
          'Please make sure your contact number is active (preferably WhatsApp), as the team or guide will contact you in advance about any updates.',
          'Depending on your selected time you can enjoy a beautiful sunset or the stunning city lights at night.',
        ],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Xəzər Dənizində Gəmi Turu: Şəhər Panoraması',
        summary: 'Romantik gəmi turu ilə Bakı buxtasını kəşf edin: gün batımında və ya şəhər işıqları altında tarixi və müasir binaları sudan seyr edin.',
        highlights: ['İşıqlandırılmış Kristal Zalı və Alov Qüllələrinə heyran qalın', 'Bakı panoramının möhtəşəm mənzərələrindən zövq alın', 'Sahil boyu rahat səyahət edin və romantik mənzərələri seyr edin', 'Bakının ən zərif və müasir gəmilərindən birində səyahət edin', 'Biznes sinifdə lüks istirahət (seçimdən asılı olaraq)'],
        description: [
          'Romantik gəmi turu ilə Bakı buxtasını kəşf edin. Həm tarixi, həm də müasir binaları günün vaxtından asılı olaraq fərqli görünüşlərdə seyr edin. Rahatlaşın və Xəzərin sakit səyahətindən zövq alın.',
          'Şəhər panoramına tamamilə yeni bucaqdan baxın: Televiziya Qülləsi, tarixi Qız Qalası və 2014-cü ildə dünyanın ən yaxşı işıqlandırılmış binası mükafatını qazanmış Alov Qüllələri. Qafqazın ən böyük ticarət mərkəzlərindən bəzilərini, o cümlədən Crescent Mall, Dəniz Mall və Bakı Gözünü də görəcəksiniz.',
          'Açıq göyərtəyə çıxaraq işıqlandırılmış Kristal Zalına və ya yola çıxma vaxtından asılı olaraq Bayraq Meydanı ilə Crescent binası arasındakı işıqlandırılmış abidələrə baxın. Dünyanın ən hündür bayrağını da görəcəksiniz: hündürlüyü 72 metrdir. Biznes sinif seçimində rahat oturacaqlar və pulsuz Azərbaycan çayı təqdim olunur.',
          'Gəminin arxasından sakitləşdirici musiqi səslənir. Güclü küləkli günlərdə tur vaxtının dəyişdirilə biləcəyini nəzərə alın.',
        ],
        includes: ['Otelə gəliş və qaytarılma', 'Giriş biletləri', 'Biznes sinif oturacaqlar (könüllü)', 'Pulsuz Azərbaycan çayı', 'Televiziya Qülləsi, Qız Qalası, Alov Qüllələri, Crescent Mall, Dəniz Mall, Bakı Gözü, Kristal Zalı, Bayraq Meydanı və Crescent binasının mənzərəsi', 'Dünyanın ən hündür bayrağının mənzərəsi', 'Sakitləşdirici musiqi', 'Gəmi restoranından yemək və içki almaq mümkündür'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: ['Alkoqol və narkotik maddələr'],
        know: [
          'Güclü küləkli günlərdə tur vaxtı dəyişdirilə bilər. Axşamlar külək adətən güclənir, ona görə 18:30 və 20:30 çıxışları 1–2 saat tez keçirilə bilər.',
          'Zəhmət olmasa, əlaqə nömrənizin aktiv olduğundan (mümkünsə WhatsApp) əmin olun: komanda və ya bələdçi yeniliklər barədə sizinlə əvvəlcədən əlaqə saxlayacaq.',
          'Seçdiyiniz vaxtdan asılı olaraq gözəl gün batımını və ya gecə şəhər işıqlarını seyr edəcəksiniz.',
        ],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Прогулка на корабле по Каспийскому морю с видами на Баку',
        summary: 'Откройте для себя Бакинскую бухту на романтической морской прогулке: исторические и современные здания с воды — на закате или в огнях ночного города.',
        highlights: ['Любуйтесь подсвеченным Хрустальным залом и Пламенными башнями', 'Великолепные виды на панораму Баку', 'Неспешный круиз вдоль побережья и романтические пейзажи', 'Путешествуйте со стилем на одном из самых элегантных и современных судов Баку', 'Роскошный отдых в бизнес-классе (в зависимости от выбранного варианта)'],
        description: [
          'Откройте Бакинскую бухту на романтической прогулке по морю. Исторические и современные здания выглядят по-разному в зависимости от времени суток. Расслабьтесь и насладитесь спокойным путешествием по Каспию.',
          'Взгляните на панораму города с нового ракурса: Телебашня, историческая Девичья башня и Пламенные башни, получившие в 2014 году награду как самое красиво подсвеченное здание мира. Вы увидите и крупнейшие торговые центры Кавказа, включая Crescent Mall, Sea Mall и Бакинское колесо обозрения.',
          'Поднимитесь на открытую палубу, чтобы увидеть подсвеченный Хрустальный зал или, в зависимости от времени отправления, памятники между площадью Флага и зданием Crescent. Вы также увидите самый большой флаг в мире высотой 72 метра. В варианте «бизнес-класс» вас ждут удобные места и бесплатный азербайджанский чай.',
          'С кормы звучит успокаивающая музыка. Обратите внимание: в дни сильного ветра время рейса может быть изменено.',
        ],
        includes: ['Трансфер из отеля и обратно', 'Входные билеты', 'Места бизнес-класса (по желанию)', 'Бесплатный азербайджанский чай', 'Виды на Телебашню, Девичью башню, Пламенные башни, Crescent Mall, Sea Mall, Бакинское колесо, Хрустальный зал, площадь Флага и здание Crescent', 'Вид на самый большой флаг в мире', 'Успокаивающая музыка', 'Еду и напитки можно купить в ресторане на борту'],
        excludes: [],
        notSuitable: [],
        bring: [],
        notAllowed: ['Алкоголь и наркотики'],
        know: [
          'В дни сильного ветра время рейса может быть изменено. Вечером ветер обычно усиливается, поэтому рейсы в 18:30 и 20:30 могут перенести на 1–2 часа раньше.',
          'Убедитесь, что ваш номер телефона активен (желательно WhatsApp): команда или гид заранее свяжутся с вами при изменениях.',
          'В зависимости от выбранного времени вы увидите красивый закат или огни ночного города.',
        ],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'baku-cooking-class',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'entertainment',
    photo: '/seed/baku-cooking-class.jpg',
    price: 35, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide',
    vehicle_features: null,
    facts: { pickup: false, private: false },
    route: '1 Fikrət Əmirov, Bakı',
    i18n: {
      en: {
        title: 'Azerbaijani Cooking Class with Lunch or Dinner',
        summary: 'Learn to cook traditional Azerbaijani dishes in a hands-on class with a local chef, then enjoy dolma, plov and qutab that you made yourself in a cozy kitchen.',
        highlights: ['Savor the flavors of Azerbaijan as you learn to cook traditional dishes', 'Enjoy a hands-on cooking class with a local chef in a cozy kitchen', 'Prepare a full meal, including dolma, plov and qutab', 'Learn about Azerbaijani cuisine and culture from your expert chef', 'Share a meal with your fellow cooks and enjoy your own creations'],
        description: [
          'Discover the authentic flavors of Azerbaijan in a hands-on cooking experience. Join an expert local chef and learn how to prepare traditional dishes passed down for generations, from fresh herbs to saffron rice.',
          'Begin with a welcome tea and an introduction to Azerbaijani cuisine, then follow step-by-step guidance. Make dolma (grape leaves stuffed with minced meat and rice), cook plov with fragrant saffron rice, dried fruits and tender meat, prepare a shepherd\'s salad and finally make qutab, thin flatbread stuffed with herbs.',
          'End the experience with a shared meal where you enjoy your own creations in a cozy, family-style kitchen.',
          'All dishes are halal (wine is optional). Wine is only included in the BBQ & Wine option, and can be added as an add-on to the other options. In the sweet-making options (sakarbura, paxlava) lunch/dinner is not included.',
        ],
        includes: ['All equipment', 'Recipes to take home (on request)', 'Lunch', 'Tea, water and snacks', 'Local chef instruction'],
        excludes: [],
        notSuitable: ['People over 95 years'],
        bring: [],
        notAllowed: [],
        know: ['The final price may vary depending on date, participants and availability.'],
        meeting: '1 Fikret Amirov, Baku, Azerbaijan (near the Museum of Modern Art).',
      },
      az: {
        title: 'Nahar və ya Şam Yeməkli Azərbaycan Mətbəx Dərsi',
        summary: 'Yerli aşpazla praktiki dərsdə ənənəvi Azərbaycan yeməklərini bişirməyi öyrənin, sonra özünüzün hazırladığınız dolma, plov və qutabı rahat mətbəxdə yeyin.',
        highlights: ['Ənənəvi yeməkləri bişirməyi öyrənərək Azərbaycanın dadlarını yaşayın', 'Rahat mətbəxdə yerli aşpazla praktiki dərsdən zövq alın', 'Dolma, plov və qutab daxil olmaqla tam yemək hazırlayın', 'Mütəxəssis aşpazdan Azərbaycan mətbəxi və mədəniyyəti haqqında öyrənin', 'Digər iştirakçılarla birlikdə öz hazırladığınız yeməkləri yeyin'],
        description: [
          'Praktiki mətbəx təcrübəsi ilə Azərbaycanın həqiqi dadlarını kəşf edin. Mütəxəssis yerli aşpazla birlikdə nəsillərdən-nəsillərə ötürülən ənənəvi yeməkləri, təzə göyərtidən zəfəranlı düyüyə qədər, hazırlamağı öyrənin.',
          'Qarşılama çayı və Azərbaycan mətbəxinə giriş ilə başlayın, sonra addım-addım rəhbərliyə əməl edin. Dolma (ət və düyü ilə doldurulmuş yarpaq dolması) hazırlayın, ətirli zəfəranlı düyü, qurudulmuş meyvələr və yumşaq ətlə plov bişirin, çoban salatı düzəldin və nəhayət göyərti ilə doldurulmuş nazik yuxa — qutab hazırlayın.',
          'Təcrübəni rahat, ailə üslubunda mətbəxdə öz hazırladığınız yeməkləri birlikdə yeməklə yekunlaşdırın.',
          'Bütün yeməklər halaldır (şərab könüllüdür). Şərab yalnız "BBQ və Şərab" seçiminə daxildir, digər seçimlərə əlavə kimi əlavə oluna bilər. Şirniyyat hazırlama seçimlərində (şəkərbura, paxlava) nahar/şam daxil deyil.',
        ],
        includes: ['Bütün avadanlıq', 'Evə aparmaq üçün reseptlər (xahişlə)', 'Nahar', 'Çay, su və qəlyanaltılar', 'Yerli aşpazın təlimatı'],
        excludes: [],
        notSuitable: ['95 yaşdan yuxarı şəxslər'],
        bring: [],
        notAllowed: [],
        know: ['Yekun qiymət tarixdən, iştirakçı sayından və mövcudluqdan asılı olaraq dəyişə bilər.'],
        meeting: 'Fikrət Əmirov 1, Bakı, Azərbaycan (Müasir İncəsənət Muzeyinin yaxınlığı).',
      },
      ru: {
        title: 'Кулинарный мастер-класс азербайджанской кухни с обедом или ужином',
        summary: 'Научитесь готовить традиционные азербайджанские блюда на практическом мастер-классе с местным шеф-поваром, а затем отведайте собственноручно приготовленные долму, плов и кутаб в уютной кухне.',
        highlights: ['Почувствуйте вкус Азербайджана, готовя традиционные блюда', 'Практический мастер-класс с местным шефом в уютной кухне', 'Приготовьте полноценный обед: долма, плов и кутаб', 'Узнайте об азербайджанской кухне и культуре от опытного шефа', 'Совместная трапеза с другими участниками из блюд, приготовленных своими руками'],
        description: [
          'Откройте для себя подлинные вкусы Азербайджана на практическом кулинарном занятии. Вместе с опытным местным шефом вы научитесь готовить традиционные блюда, передававшиеся из поколения в поколение — от свежей зелени до шафранового риса.',
          'Начните с приветственного чая и знакомства с азербайджанской кухней, а затем следуйте пошаговым указаниям шефа. Приготовьте долму (виноградные листья с мясом и рисом), плов с ароматным шафрановым рисом, сухофруктами и нежным мясом, пастушеский салат и, наконец, кутаб — тонкую лепёшку с зеленью.',
          'Завершите занятие общей трапезой, где вы отведаете собственные творения в уютной, по-домашнему тёплой кухне.',
          'Все блюда халяль (вино — по желанию). Вино входит только в вариант «BBQ и вино» и может быть добавлено к остальным вариантам как дополнение. В вариантах со сладостями (шекербура, пахлава) обед/ужин не включён.',
        ],
        includes: ['Всё оборудование', 'Рецепты с собой (по запросу)', 'Обед', 'Чай, вода и закуски', 'Инструктаж местного шеф-повара'],
        excludes: [],
        notSuitable: ['Людям старше 95 лет'],
        bring: [],
        notAllowed: [],
        know: ['Итоговая цена может меняться в зависимости от даты, числа участников и наличия мест.'],
        meeting: 'Фикрета Амирова, 1, Баку, Азербайджан (рядом с Музеем современного искусства).',
      },
    },
  },

  {
    key: 'baku-food-tour-market-teahouse',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'food',
    photo: '/seed/baku-food-tour-market-teahouse.jpg',
    price: 30, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide,evening_tea',
    vehicle_features: 'ac',
    facts: { duration_hours: 4, guide_languages: ['en'], pickup: true, private: false },
    route: 'Hotel pickup (outside central Baku)',
    i18n: {
      en: {
        title: 'Baku Food Tour: Local Market, Tea House & Azerbaijani Feast',
        summary: 'Taste Baku like a local: spice markets, century-old tea houses and a legendary Azerbaijani feast. Small groups, all tastings included.',
        highlights: ['Explore Taza Bazaar, Baku\'s most iconic open-air market', 'Meet vendors and learn insider tips for shopping like a local', 'Tea and baklava in a traditional tea house', 'Taste freshly made qutab and saffron-infused plov', 'Finish with a lavish lunch at Shirvanshah Restaurant'],
        description: [
          'Dive into the rich and aromatic world of Azerbaijani cuisine on this premium 4-hour food tour through the most flavorful corners of Baku. Led by a passionate local guide, you explore vibrant markets, sip traditional tea in a century-old tea house and feast on authentic dishes at one of Baku\'s most celebrated restaurants.',
          'This is a full sensory experience where food tells the story of Azerbaijan\'s Silk Road heritage, its Persian, Ottoman and Russian influences, and the warmth of its people.',
          'What you will experience: start at Taza Bazaar, overflowing with spices, dried fruits, fresh herbs and local cheeses; warm up with a glass of aromatic black tea (çay) and golden baklava (paxlava); taste freshly made qutab with cheese, greens or pumpkin; discover saffron-infused plov, the king of Azerbaijani cuisine; and end with a lavish spread of dolma and kebab.',
          'Your guide is a Baku native and certified culinary storyteller, fluent in English.',
        ],
        includes: ['Private air-conditioned vehicle for pickup and drop-off', 'All food and drink tastings throughout the tour', 'Full tasting lunch at Shirvanshah Restaurant', 'Professional English-speaking local food guide', 'Personalised bazaar shopping guide and spice recommendations', 'Hotel pickup outside central Baku'],
        excludes: ['Personal purchases at the bazaar', 'Gratuities (optional but appreciated)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['The tour lasts about 4 hours and runs in small groups.'],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Bakı Qastronomiya Turu: Yerli Bazar, Çayxana və Azərbaycan Süfrəsi',
        summary: 'Bakını yerli kimi dadın: ədviyyat bazarları, əsrlik çayxanalar və əfsanəvi Azərbaycan süfrəsi. Kiçik qruplar, bütün dadma proqramı daxildir.',
        highlights: ['Bakının ən məşhur açıq hava bazarı olan Təzə Bazarı kəşf edin', 'Satıcılarla tanış olun və yerli kimi alış-veriş sirləri öyrənin', 'Ənənəvi çayxanada çay və paxlava', 'Təzə hazırlanmış qutab və zəfəranlı plovu dadın', 'Şirvanşah Restoranında zəngin nahar ilə yekunlaşdırın'],
        description: [
          'Bakının ən ləzzətli guşələrindən keçən bu premium 4 saatlıq qastronomiya turunda Azərbaycan mətbəxinin zəngin və ətirli dünyasına baş vurun. Həvəsli yerli bələdçinin müşayiəti ilə canlı bazarları gəzəcək, əsrlik çayxanada ənənəvi çay içəcək və Bakının ən məşhur restoranlarından birində əsl yeməklərdən dadacaqsınız.',
          'Bu, yeməyin Azərbaycanın İpək Yolu irsini, fars, Osmanlı və rus təsirlərini, eləcə də xalqın isti münasibətini danışdığı tam hissiyyat təcrübəsidir.',
          'Sizi nə gözləyir: ədviyyat, qurudulmuş meyvə, təzə göyərti və yerli pendirlərlə dolu Təzə Bazarda start; ətirli qara çay (çay) və qızılı paxlava ilə ilıqlaşma; pendir, göyərti və ya balqabaqlı təzə qutab; Azərbaycan mətbəxinin kralı olan zəfəranlı plovun sirləri; və dolma ilə kabab süfrəsi ilə yekun.',
          'Bələdçiniz Bakılı, sertifikatlı qastronomiya hekayəçisidir və səlis ingilis dilində danışır.',
        ],
        includes: ['Gediş-gəliş üçün kondisionerli şəxsi avtomobil', 'Tur boyu bütün yemək və içki dadma proqramı', 'Şirvanşah Restoranında tam dadma naharı', 'Peşəkar ingilisdilli yerli qastronomiya bələdçisi', 'Fərdi bazar alış-veriş bələdçisi və ədviyyat tövsiyələri', 'Mərkəzi Bakıdan kənarda otelə gəliş'],
        excludes: ['Bazarda şəxsi alışlar', 'Çay pulu (könüllü, lakin xoş qarşılanır)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Tur təxminən 4 saat çəkir və kiçik qruplarla keçirilir.'],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Гастротур по Баку: местный рынок, чайхана и азербайджанское застолье',
        summary: 'Попробуйте Баку как местный житель: рынки специй, чайханы с вековой историей и легендарное азербайджанское застолье. Малые группы, все дегустации включены.',
        highlights: ['Рынок Таза Базар — самый знаковый открытый рынок Баку', 'Знакомство с торговцами и советы, как покупать по-местному', 'Чай и пахлава в традиционной чайхане', 'Свежий кутаб и плов с шафраном', 'Щедрый обед в ресторане «Ширваншах»'],
        description: [
          'Окунитесь в богатый и ароматный мир азербайджанской кухни в рамках этого премиального 4-часового гастротура по самым вкусным уголкам Баку. Увлечённый местный гид проведёт вас по живым рынкам, угостит чаем в чайхане с вековой историей и накормит настоящими блюдами в одном из самых известных ресторанов города.',
          'Это целое сенсорное путешествие, в котором еда рассказывает об истории Великого шёлкового пути, персидском, османском и русском влиянии и о душевной теплоте людей.',
          'Что вас ждёт: старт на рынке Таза Базар с горами специй, сухофруктов, свежей зелени и местных сыров; стакан ароматного чёрного чая (чай) с золотистой пахлавой; свежий кутаб с сыром, зеленью или тыквой; плов с шафраном — король азербайджанской кухни; и щедрое угощение из долмы и кебаба.',
          'Ваш гид — бакинец и сертифицированный «кулинарный рассказчик», свободно говорящий по-английски.',
        ],
        includes: ['Частный автомобиль с кондиционером для трансфера', 'Все дегустации еды и напитков в течение экскурсии', 'Полноценный дегустационный обед в ресторане «Ширваншах»', 'Профессиональный англоговорящий местный гид по еде', 'Персональные советы по покупкам на рынке и подбору специй', 'Трансфер из отелей за пределами центра Баку'],
        excludes: ['Личные покупки на рынке', 'Чаевые (по желанию, но приветствуются)'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Экскурсия длится около 4 часов и проходит в малых группах.'],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'baku-flavors-tasting',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'food',
    photo: '/seed/baku-flavors-tasting.jpg',
    price: 55, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide,evening_tea',
    vehicle_features: null,
    facts: { guide_languages: ['en', 'ar'], pickup: false, private: false },
    route: 'In front of Baku Mall',
    i18n: {
      en: {
        title: 'Flavors of Baku: Guided Food Tasting Tour with Tea Session',
        summary: 'Discover Baku\'s culinary culture on a guided food tasting tour: 5 tastings of authentic Azerbaijani flavors and a relaxing traditional tea session.',
        highlights: ['Savor the flavors of Baku on a guided food tasting tour', 'Enjoy 5 tastings that highlight authentic Azerbaijani flavors', 'Discover the city\'s culinary culture with a local foodie guide', 'Explore lively streets and local spots loved by residents', 'Relax with a traditional tea session, an essential part of Azerbaijani culture'],
        description: [
          'Join a guided tasting experience in Baku and step into the heart of the city\'s culinary culture as you explore lively streets and local spots loved by residents.',
          'Led by a knowledgeable local foodie, enjoy 5 carefully curated tastings that highlight authentic Azerbaijani flavors, from savory delights to sweet specialties. Each dish is handpicked to reflect the region\'s heritage and warm hospitality.',
          'Round off your experience with a traditional tea session, an essential part of Azerbaijani culture. Vegetarian and non-vegetarian options are available.',
        ],
        includes: ['English/Arabic-speaking live tour guide', 'Customized walking itinerary', 'Local recommendations for food, shopping and sightseeing', 'Cultural explanations and translation assistance when needed'],
        excludes: ['Personal expenses', 'Tips'],
        notSuitable: ['Pregnant women', 'People with mobility impairments', 'Wheelchair users'],
        bring: ['Comfortable shoes', 'Sunglasses', 'Sun hat', 'Sunscreen', 'Comfortable clothes', 'Reusable water bottle'],
        notAllowed: ['Smoking', 'Intoxication', 'Alcohol and drugs', 'Littering'],
        know: ['Come hungry and stay curious.'],
        meeting: 'We meet in front of Baku Mall. Please arrive on time to avoid delaying the start of the tour.',
      },
      az: {
        title: 'Bakının Dadları: Çay Seanslı Bələdçili Dadma Turu',
        summary: 'Bələdçili dadma turunda Bakının qastronomiya mədəniyyətini kəşf edin: 5 əsl Azərbaycan dadı və ənənəvi çay seansı ilə rahatlıq.',
        highlights: ['Bələdçili dadma turunda Bakının dadlarını yaşayın', 'Əsl Azərbaycan dadlarını təqdim edən 5 dadma', 'Yerli qastronomiya bələdçisi ilə şəhərin yemək mədəniyyətini kəşf edin', 'Sakinlərin sevdiyi canlı küçələri və yerli məkanları gəzin', 'Azərbaycan mədəniyyətinin ayrılmaz hissəsi olan ənənəvi çay seansı ilə rahatlayın'],
        description: [
          'Bakıda bələdçili dadma təcrübəsinə qoşulun və sakinlərin sevdiyi canlı küçələri və yerli məkanları gəzərək şəhərin qastronomiya mədəniyyətinin mərkəzinə daxil olun.',
          'Bilikli yerli qastronomiya bələdçisinin rəhbərliyi ilə acıdan şirinə qədər əsl Azərbaycan dadlarını təqdim edən, diqqətlə seçilmiş 5 dadmadan zövq alın. Hər yemək regionun irsini və qonaqpərvərliyini əks etdirmək üçün seçilib.',
          'Təcrübəni Azərbaycan mədəniyyətinin əsas hissəsi olan ənənəvi çay seansı ilə tamamlayın. Vegetarian və qeyri-vegetarian seçimlər mövcuddur.',
        ],
        includes: ['İngilis/ərəbdilli canlı tur bələdçisi', 'Fərdiləşdirilmiş piyada marşrut', 'Yemək, alış-veriş və görməli yerlər üzrə yerli tövsiyələr', 'Mədəni izahatlar və lazım olduqda tərcümə köməyi'],
        excludes: ['Şəxsi xərclər', 'Çay pulu'],
        notSuitable: ['Hamilə qadınlar', 'Hərəkət məhdudiyyəti olanlar', 'Əlil arabasından istifadə edənlər'],
        bring: ['Rahat ayaqqabı', 'Günəş eynəyi', 'Günəş şlyapası', 'Günəş kremi', 'Rahat geyim', 'Təkrar istifadə olunan su şüşəsi'],
        notAllowed: ['Siqaret çəkmək', 'Sərxoşluq', 'Alkoqol və narkotik maddələr', 'Zibil atmaq'],
        know: ['Ac gəlin və maraqlı olun.'],
        meeting: 'Baku Mall-un qarşısında görüşürük. Turun gecikməməsi üçün zəhmət olmasa vaxtında gəlin.',
      },
      ru: {
        title: 'Вкусы Баку: гастрономический тур с дегустацией и чайной церемонией',
        summary: 'Познакомьтесь с кулинарной культурой Баку на экскурсии с дегустацией: 5 подлинных азербайджанских вкусов и расслабляющая традиционная чайная церемония.',
        highlights: ['Почувствуйте вкус Баку на гастрономической экскурсии с гидом', '5 дегустаций подлинных азербайджанских блюд', 'Кулинарная культура города глазами местного гурмана', 'Оживлённые улицы и места, любимые горожанами', 'Традиционная чайная церемония — неотъемлемая часть азербайджанской культуры'],
        description: [
          'Присоединяйтесь к дегустационной экскурсии по Баку и окунитесь в кулинарную культуру города, прогуливаясь по оживлённым улицам и местам, которые любят сами жители.',
          'Под руководством знающего местного гурмана вас ждут 5 тщательно подобранных дегустаций подлинных азербайджанских вкусов — от пикантных блюд до сладостей. Каждое блюдо отобрано так, чтобы отражать наследие региона и его гостеприимство.',
          'Завершите экскурсию традиционной чайной церемонией — важной частью азербайджанской культуры. Доступны вегетарианские и невегетарианские варианты.',
        ],
        includes: ['Живой гид, говорящий по-английски и по-арабски', 'Индивидуальный пеший маршрут', 'Местные рекомендации по еде, покупкам и достопримечательностям', 'Культурные пояснения и помощь с переводом при необходимости'],
        excludes: ['Личные расходы', 'Чаевые'],
        notSuitable: ['Беременным женщинам', 'Людям с ограниченной подвижностью', 'Пользователям инвалидных колясок'],
        bring: ['Удобная обувь', 'Солнцезащитные очки', 'Головной убор от солнца', 'Солнцезащитный крем', 'Удобная одежда', 'Многоразовая бутылка для воды'],
        notAllowed: ['Курение', 'Нахождение в состоянии опьянения', 'Алкоголь и наркотики', 'Мусорить'],
        know: ['Приходите голодными и любознательными.'],
        meeting: 'Встречаемся перед торговым центром Baku Mall. Пожалуйста, приходите вовремя, чтобы не задерживать начало экскурсии.',
      },
    },
  },

  {
    key: 'baku-street-food',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'food',
    photo: '/seed/baku-street-food.jpg',
    price: 40, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: 'guide',
    vehicle_features: 'ac',
    facts: { pickup: true, private: false },
    route: 'Double Gates of the Old City (Icherisheher)',
    i18n: {
      en: {
        title: 'Baku Street Food Tour',
        summary: 'A gastronomic adventure through the charming streets of Baku, savoring the essence of Azerbaijani culture one delicious bite at a time.',
        highlights: ['Relish Azerbaijani street flavors', 'Immerse yourself in Baku\'s vibrant food scene', 'Discover cherished street eats', 'Learn food tales from the heart', 'Engage with friendly vendors'],
        description: [
          'Prepare your taste buds for a mouthwatering journey through the bustling streets of Baku. Your expert guide leads you through the city\'s culinary hotspots, from fragrant spices to sizzling skewers, where each bite tells a story of Azerbaijan\'s rich food heritage.',
          'Taste the iconic lamb kebabs, crispy qutabs (savory stuffed pastries) and aromatic pilaf, and sample traditional sweets like baklava and shekerbura. You will also be taken off the beaten path to hidden food gems and hole-in-the-wall eateries cherished by locals.',
          'As you eat, your guide shares insights into Azerbaijani culture and food traditions. Experience the lively ambiance of Baku\'s food markets and street stalls and engage with friendly vendors.',
          'Tours run in small groups for a personalized, intimate experience. Vegetarian options are available for guests with dietary restrictions.',
        ],
        includes: ['Hotel pickup and drop-off', 'Private transportation', 'Air-conditioned vehicle', 'Local street food', 'Local drinks'],
        excludes: ['Gratuities'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Small-group tour with vegetarian options available.'],
        meeting: 'Meeting point: the Double Gates of the Old City (Icherisheher), the main entrance to the Old City walls. Your guide will be waiting in front of the gates.',
      },
      az: {
        title: 'Bakı Küçə Yeməkləri Turu',
        summary: 'Bakının füsunkar küçələrində qastronomik macəra: Azərbaycan mədəniyyətinin mahiyyətini hər ləzzətli tikə ilə dadın.',
        highlights: ['Azərbaycan küçə dadlarından zövq alın', 'Bakının canlı yemək dünyasına qərq olun', 'Sevilən küçə yeməklərini kəşf edin', 'Ürəkdən gələn yemək hekayələrini öyrənin', 'Mehriban satıcılarla ünsiyyət qurun'],
        description: [
          'Dad reseptorlarınızı Bakının canlı küçələrindən keçən ağızsulandıran səyahətə hazırlayın. Mütəxəssis bələdçiniz sizi ətirli ədviyyatlardan cızıldayan şişlərə qədər şəhərin qastronomik məkanlarına aparır; hər tikə Azərbaycanın zəngin yemək irsinin hekayəsini danışır.',
          'Məşhur quzu kababını, xırtıldayan qutabları (ətli-göyərtili xəmir yeməyi) və ətirli pilovu dadın, baklava və şəkərbura kimi ənənəvi şirniyyatlardan dadın. Həmçinin yerlilərin sevdiyi gizli yemək məkanlarına və kiçik yeməkxanalara aparılacaqsınız.',
          'Yemək zamanı bələdçi Azərbaycan mədəniyyəti və yemək ənənələri haqqında məlumat verir. Bakının yemək bazarlarının və küçə piştaxtalarının canlı mühitini yaşayın və mehriban satıcılarla ünsiyyət qurun.',
          'Fərdi və səmimi təcrübə üçün turlar kiçik qruplarla keçirilir. Pəhriz məhdudiyyəti olan qonaqlar üçün vegetarian seçimlər mövcuddur.',
        ],
        includes: ['Otelə gəliş və qaytarılma', 'Şəxsi nəqliyyat', 'Kondisionerli avtomobil', 'Yerli küçə yeməkləri', 'Yerli içkilər'],
        excludes: ['Çay pulu'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Kiçik qrup turu, vegetarian seçimlər mövcuddur.'],
        meeting: 'Görüş nöqtəsi: İçərişəhərin Qoşa Qapıları, qala divarlarının əsas girişi. Bələdçiniz qapıların qarşısında sizi gözləyəcək.',
      },
      ru: {
        title: 'Тур по уличной еде Баку',
        summary: 'Гастрономическое приключение по очаровательным улицам Баку: почувствуйте суть азербайджанской культуры, откусывая кусочек за кусочком.',
        highlights: ['Насладитесь азербайджанскими уличными вкусами', 'Погрузитесь в яркую гастрономическую жизнь Баку', 'Откройте для себя любимую уличную еду', 'Узнайте истории еды, рассказанные от души', 'Пообщайтесь с дружелюбными торговцами'],
        description: [
          'Приготовьтесь к аппетитному путешествию по шумным улицам Баку. Гид-эксперт проведёт вас по кулинарным «горячим точкам» города — от ароматных специй до шипящих шашлыков; каждый кусочек рассказывает историю богатого гастрономического наследия Азербайджана.',
          'Попробуйте легендарный шашлык из баранины, хрустящие кутабы (пирожки с начинкой) и ароматный плов, а также традиционные сладости — пахлаву и шекербуру. Вас также проведут по нехоженым тропам к скрытым гастрономическим жемчужинам и маленьким закусочным, любимым местными.',
          'Пока вы пробуете блюда, гид расскажет о культуре и кулинарных традициях Азербайджана. Почувствуйте живую атмосферу бакинских продуктовых рынков и уличных лотков и пообщайтесь с дружелюбными торговцами.',
          'Для комфортной и камерной атмосферы экскурсии проходят в малых группах. Для гостей с пищевыми ограничениями есть вегетарианские варианты.',
        ],
        includes: ['Трансфер из отеля и обратно', 'Индивидуальный транспорт', 'Автомобиль с кондиционером', 'Местная уличная еда', 'Местные напитки'],
        excludes: ['Чаевые'],
        notSuitable: [],
        bring: [],
        notAllowed: [],
        know: ['Экскурсия в малой группе, доступны вегетарианские варианты.'],
        meeting: 'Место встречи: Двойные ворота Старого города (Ичери-шехер) — главный вход в крепостные стены. Гид будет ждать вас перед воротами.',
      },
    },
  },

  {
    key: 'baku-bazaar-tour',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'food',
    photo: '/seed/baku-bazaar-tour.jpg',
    price: 25, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 8,
    features: '',
    vehicle_features: null,
    facts: { pickup: true, private: false },
    route: 'Hotel pickup (Baku)',
    i18n: {
      en: {
        title: 'Baku Bazaar Tour: Flavors, Crafts and Sweet Memories',
        summary: 'Experience the vibrant culture of Baku through its lively markets and hidden gems: visit a local market, see shops showcasing Azerbaijan\'s craftsmanship and sample traditional desserts.',
        highlights: ['Discover the vibrant culture of Baku through its lively markets and hidden gems', 'Explore a local market and see how it brings the community together', 'Visit shops that showcase Azerbaijan\'s rich craftsmanship', 'Watch artisans at work and discover the stories behind their creations', 'Sample traditional Azerbaijani desserts like pakhlava and shekerbura'],
        description: [
          'Begin at a local market where you stroll through stalls overflowing with fresh fruits, vegetables and aromatic herbs. Discover the spices at the heart of Azerbaijani cuisine, and traditional items like dried fruits, nuts and regional cheeses, while learning about the daily rhythm of the market.',
          'Then visit shops that highlight Azerbaijan\'s artistic traditions: handmade carpets with intricate designs, skillfully crafted ceramics and embroidered textiles. Meet artisans who share the secrets of their crafts and demonstrate techniques passed down through generations.',
          'The tour concludes at sweet shops beloved by locals, where you taste traditional desserts such as pakhlava, shekerbura and qoghal and learn about their place in Azerbaijani celebrations. Each guest receives a piece of freshly made baklava to take home.',
        ],
        includes: ['Hotel pickup', 'Comfortable transportation', 'Visit to a local market', 'Exploration of stalls with fresh produce, spices and traditional Azerbaijani delicacies', 'Visit to shops showcasing Azerbaijan\'s craftsmanship', 'Sampling of authentic desserts at a hidden sweet shop', 'A piece of freshly made baklava to take home', 'Return to hotel'],
        excludes: ['Personal expenses'],
        notSuitable: ['People with animal allergies', 'People with food allergies'],
        bring: ['Passport'],
        notAllowed: ['Pets', 'Smoking'],
        know: [],
        meeting: 'You will be picked up from any address within the highlighted area. Confirm your pickup address when booking. Drop-off is at the same place.',
      },
      az: {
        title: 'Bakı Bazar Turu: Dadlar, Sənətkarlıq və Şirin Xatirələr',
        summary: 'Bakının canlı bazarları və gizli məkanları vasitəsilə şəhərin mədəniyyətini yaşayın: yerli bazara baş çəkin, Azərbaycan sənətkarlığını nümayiş etdirən mağazaları görün və ənənəvi desertləri dadın.',
        highlights: ['Canlı bazarlar və gizli məkanlar vasitəsilə Bakının mədəniyyətini kəşf edin', 'Yerli bazarı gəzin və onun icmanı necə birləşdirdiyini görün', 'Azərbaycanın zəngin sənətkarlığını nümayiş etdirən mağazalara baş çəkin', 'Sənətkarların işini izləyin və əsərlərinin arxasındakı hekayələri öyrənin', 'Paxlava və şəkərbura kimi ənənəvi Azərbaycan desertlərini dadın'],
        description: [
          'Turu təzə meyvə, tərəvəz və ətirli göyərti ilə dolu piştaxtalar arasında gəzərək yerli bazarda başlayın. Azərbaycan mətbəxinin əsasını təşkil edən ədviyyatları, qurudulmuş meyvələr, qoz-fındıq və regional pendirlər kimi ənənəvi məhsulları kəşf edin, bazarın gündəlik ritmi ilə tanış olun.',
          'Sonra Azərbaycanın sənət ənənələrini nümayiş etdirən mağazalara baş çəkin: mürəkkəb naxışlı əl işi xalçalar, məharətlə hazırlanmış keramika və tikmə parçalar. Sənətkarların nəsillərdən-nəsillərə ötürülən üsulları və sənət sirlərini necə paylaşdığını görün.',
          'Tur yerlilərin sevdiyi şirniyyat dükanlarında tamamlanır: burada paxlava, şəkərbura və qoğal kimi ənənəvi desertləri dadır və onların Azərbaycan bayramlarındakı yerini öyrənirsiniz. Hər qonağa evə aparmaq üçün təzə hazırlanmış bir tikə paxlava hədiyyə olunur.',
        ],
        includes: ['Otelə gəliş', 'Rahat nəqliyyat', 'Yerli bazara ziyarət', 'Təzə məhsul, ədviyyat və ənənəvi Azərbaycan ləzzətləri olan piştaxtaların gəzintisi', 'Azərbaycan sənətkarlığını nümayiş etdirən mağazalara ziyarət', 'Gizli şirniyyat dükanında əsl desertlərin dadılması', 'Evə aparmaq üçün təzə hazırlanmış bir tikə paxlava', 'Otelə qaytarılma'],
        excludes: ['Şəxsi xərclər'],
        notSuitable: ['Heyvanlara allergiyası olanlar', 'Qida allergiyası olanlar'],
        bring: ['Pasport'],
        notAllowed: ['Ev heyvanları', 'Siqaret çəkmək'],
        know: [],
        meeting: 'Vurğulanmış ərazi daxilindəki istənilən ünvandan götürülürsünüz. Ünvanı bron zamanı təsdiqləyin. Qaytarılma da eyni yerədir.',
      },
      ru: {
        title: 'Тур по рынкам Баку: вкусы, ремёсла и сладкие воспоминания',
        summary: 'Откройте яркую культуру Баку через оживлённые рынки и скрытые жемчужины: загляните на местный рынок, в мастерские ремёсел и попробуйте традиционные десерты.',
        highlights: ['Яркая культура Баку через оживлённые рынки и скрытые уголки', 'Местный рынок — место, которое объединяет людей', 'Магазины, показывающие богатое ремесленное наследие Азербайджана', 'Наблюдайте за работой мастеров и узнавайте истории их изделий', 'Традиционные десерты: пахлава и шекербура'],
        description: [
          'Начните с местного рынка: пройдитесь между прилавками, ломящимися от свежих фруктов, овощей и ароматной зелени. Узнайте о специях, лежащих в основе азербайджанской кухни, о сухофруктах, орехах и региональных сырах, а заодно о ежедневном ритме рынка.',
          'Затем загляните в магазины, отражающие художественные традиции Азербайджана: ковры ручной работы со сложными узорами, искусная керамика и вышитый текстиль. Познакомьтесь с мастерами, которые делятся секретами ремесла и показывают приёмы, передаваемые из поколения в поколение.',
          'Экскурсия завершается в любимых местными кондитерских, где вы попробуете пахлаву, шекербуру и гогал и узнаете, какую роль эти сладости играют в азербайджанских праздниках. Каждый гость получает в подарок свежую пахлаву с собой.',
        ],
        includes: ['Трансфер из отеля', 'Комфортабельный транспорт', 'Посещение местного рынка', 'Знакомство с прилавками со свежими продуктами, специями и традиционными азербайджанскими лакомствами', 'Посещение магазинов, демонстрирующих ремёсла Азербайджана', 'Дегустация настоящих десертов в скрытой кондитерской', 'Кусочек свежей пахлавы с собой', 'Возвращение в отель'],
        excludes: ['Личные расходы'],
        notSuitable: ['Людям с аллергией на животных', 'Людям с пищевой аллергией'],
        bring: ['Паспорт'],
        notAllowed: ['Домашние животные', 'Курение'],
        know: [],
        meeting: 'Вас заберут с любого адреса в выделенной зоне. Адрес подтверждается при бронировании. Возвращение — в то же место.',
      },
    },
  },

  {
    key: 'baku-best-of-walking',
    operator: 'Baku City Guides',
    location: 'Bakı',
    category: 'history',
    photo: '/seed/baku-best-of-walking.jpg',
    price: 35, // AZN per person, as listed on GetYourGuide
    duration_days: 1,
    min_participants: 2,
    max_participants: 12,
    features: 'guide',
    vehicle_features: null,
    facts: { duration_hours: 4, pickup: false, private: false },
    route: 'Highland Park, Baku',
    i18n: {
      en: {
        title: 'Best of Baku: 4-Hour Walking Tour of Historic and Modern Baku',
        summary: 'Discover the soul of Baku in just 4 hours on this all-in-one city experience: from panoramic views to ancient alleyways, the historic and modern charm of the capital.',
        highlights: ['Enjoy panoramic views from Highland Park and the funicular', 'Explore centuries of history in Baku\'s UNESCO-listed Old City', 'Walk along Baku\'s waterfront and vibrant Nizami Street', 'See 30+ top attractions in a single tour', 'Photo stops at iconic landmarks like the Carpet Museum and Flame Towers'],
        description: [
          'Begin at Highland Park, with panoramic views of Baku Bay and the iconic Flame Towers. Visit Martyrs\' Lane and the Eternal Flame, a poignant tribute to Azerbaijan\'s history.',
          'Take a ride on the Baku Funicular and continue to the Carpet Museum for a photo stop, admiring its design inspired by a rolled-up carpet. Stroll along Baku Boulevard and explore Mini-Venice, a charming area of canals and bridges. Visit Philharmonia Garden and the neoclassical Philharmonic Hall.',
          'Head into the UNESCO-listed Old City: the Metro Station, Baku Duma, Aliagha Vahid Monument and the Museum of Miniature Books, the Shirvanshahs\' Palace, Muhammad Mosque, Juma Mosque, Maiden Tower and Hajinski Palace. Visit the Bukhara and Multani Caravanserais and see the Monument to Lovers and Cats, Baku Khans\' Palace, Double Gates and the Underground Bath.',
          'End at the Nizami Museum of Literature, Fountain Square and Nizami Street, a vibrant shopping and dining area.',
        ],
        includes: ['Live tour guide', 'Walking tour', 'Funicular ride'],
        excludes: ['Food and drinks'],
        notSuitable: [],
        bring: ['Comfortable shoes', 'Camera'],
        notAllowed: [],
        know: ['Wear comfortable shoes, as there will be a lot of walking.', 'Bring a camera for photo opportunities.'],
        meeting: 'The tour starts at Highland Park in Baku. Please arrive a few minutes early.',
      },
      az: {
        title: 'Bakının Ən Yaxşısı: Tarixi və Müasir Bakıya 4 Saatlıq Piyada Tur',
        summary: 'Hərtərəfli şəhər təcrübəsi ilə Bakının ruhunu cəmi 4 saata kəşf edin: panoram mənzərələrdən qədim döngələrə qədər paytaxtın tarixi və müasir cazibəsi.',
        highlights: ['Dağüstü Parkdan və funikulyordan panoram mənzərələrdən zövq alın', 'UNESCO siyahısındakı Bakı Köhnə Şəhərində əsrlərin tarixini kəşf edin', 'Bakı sahil bulvarı və canlı Nizami küçəsi boyunca gəzin', 'Bir turda 30-dan çox əsas görməli yer', 'Xalça Muzeyi və Alov Qüllələri kimi məşhur abidələrdə foto fasilələri'],
        description: [
          'Bakı buxtasının və məşhur Alov Qüllələrinin panoram mənzərəsini təqdim edən Dağüstü Parkdan başlayın. Azərbaycan tarixinə təsirli ehtiram olan Şəhidlər Xiyabanını və Əbədi Məşəli ziyarət edin.',
          'Bakı Funikulyoru ilə qalxın və foto fasiləsi üçün rulon halına salınmış xalçadan ilhamlanmış dizaynı ilə seçilən Xalça Muzeyinə yollanın. Bakı Bulvarı boyunca gəzin, kanallar və körpülərlə dolu füsunkar Kiçik Venesiya zonasını kəşf edin. Filarmoniya Bağını və neoklassik Filarmoniya Zalını ziyarət edin.',
          'UNESCO siyahısındakı İçərişəhərə daxil olun: Metro stansiyası, Bakı Dumasi, Əliağa Vahid abidəsi və Miniatür Kitablar Muzeyi, Şirvanşahlar Sarayı, Məhəmməd Məscidi, Cümə Məscidi, Qız Qalası və Hacınski Sarayı. Buxara və Multani karvansaralarına baş çəkin, Aşiqlər və Pişiklər abidəsini, Bakı Xanları Sarayını, Qoşa Qapıları və Yeraltı Hamamı görün.',
          'Nizami Ədəbiyyat Muzeyi, Fəvvarələr meydanı və canlı alış-veriş və yemək zonası olan Nizami küçəsi ilə turu başa vurun.',
        ],
        includes: ['Canlı tur bələdçisi', 'Piyada tur', 'Funikulyor gəzintisi'],
        excludes: ['Yemək və içkilər'],
        notSuitable: [],
        bring: ['Rahat ayaqqabı', 'Fotoaparat'],
        notAllowed: [],
        know: ['Çoxlu piyada gəzinti olacağı üçün rahat ayaqqabı geyin.', 'Foto imkanları üçün fotoaparat götürün.'],
        meeting: 'Tur Bakıda Dağüstü Parkdan başlayır. Zəhmət olmasa bir neçə dəqiqə tez gəlin.',
      },
      ru: {
        title: 'Лучшее в Баку: 4-часовая пешая экскурсия по историческому и современному Баку',
        summary: 'Откройте душу Баку всего за 4 часа на этой универсальной экскурсии: от панорамных видов до древних переулков — исторический и современный облик столицы.',
        highlights: ['Панорамные виды с Нагорного парка и поездка на фуникулёре', 'Многовековая история Старого города Баку из списка ЮНЕСКО', 'Прогулка по набережной и оживлённой улице Низами', 'Более 30 главных достопримечательностей за одну экскурсию', 'Фотоостановки у знаковых мест — Музея ковра и Пламенных башен'],
        description: [
          'Начните с Нагорного парка с панорамными видами на Бакинскую бухту и знаменитые Пламенные башни. Посетите Аллею шехидов и Вечный огонь — трогательную дань истории Азербайджана.',
          'Прокатитесь на бакинском фуникулёре и отправляйтесь к Музею ковра для фотоостановки — его дизайн вдохновлён свёрнутым ковром. Прогуляйтесь по Бакинскому бульвару и «Маленькой Венеции» с каналами и мостиками. Загляните в сад Филармонии и неоклассическое здание Филармонии.',
          'Войдите в Старый город из списка ЮНЕСКО: станция метро, Бакинская дума, памятник Алиаге Вахиду, Музей миниатюрной книги, Дворец Ширваншахов, мечеть Мухаммеда, Джума-мечеть, Девичья башня и дворец Гаджинского. Посетите Бухарский и Мултанский караван-сараи, увидите памятник влюблённым и кошкам, Дворец бакинских ханов, Двойные ворота и подземную баню.',
          'Завершите экскурсию у Музея азербайджанской литературы имени Низами, на площади Фонтанов и на улице Низами — оживлённой зоне магазинов и ресторанов.',
        ],
        includes: ['Живой гид', 'Пешая экскурсия', 'Поездка на фуникулёре'],
        excludes: ['Еда и напитки'],
        notSuitable: [],
        bring: ['Удобная обувь', 'Фотоаппарат'],
        notAllowed: [],
        know: ['Наденьте удобную обувь — предстоит много ходить.', 'Возьмите фотоаппарат для красивых кадров.'],
        meeting: 'Экскурсия начинается в Нагорном парке Баку. Пожалуйста, приходите на несколько минут раньше.',
      },
    },
  },
];
